[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_21_28"

[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_31_32"

[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_31_9"

[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_34_22"

[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_41_28"

[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_42_18"

[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_44_5"

[[spawn]]
obj = "obj.mm_skeleton_bones"
coords = "0_42_142_51_9"

