[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_12_20"

[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_13_39"

[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_25_14"

[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_28_50"

[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_35_46"

[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_43_13"

[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_48_46"

[[spawn]]
obj = "obj.bones_burnt"
coords = "0_22_157_51_25"

[[spawn]]
obj = "obj.firerune"
coords = "0_22_157_11_14"

[[spawn]]
obj = "obj.firerune"
coords = "0_22_157_13_48"

[[spawn]]
obj = "obj.firerune"
coords = "0_22_157_42_51"

[[spawn]]
obj = "obj.firerune"
coords = "0_22_157_46_15"

