[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_38_36"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_38_41"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_38_45"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_39_31"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_40_26"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_45_38"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_45_40"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_48_35"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_48_40"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_53_45"

[[spawn]]
obj = "obj.red_spiders_eggs"
coords = "0_28_155_58_40"

