[[spawn]]
obj = "obj.bones"
coords = "2_35_93_1_7"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_20_60"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_2_45"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_3_16"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_3_41"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_47_4"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_55_5"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_5_11"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_60_53"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_63_34"

[[spawn]]
obj = "obj.bones"
coords = "2_35_93_7_58"

[[spawn]]
obj = "obj.bones"
coords = "2_35_94_26_2"

[[spawn]]
obj = "obj.bones"
coords = "2_35_94_31_0"

[[spawn]]
obj = "obj.bones"
coords = "2_35_94_39_0"

[[spawn]]
obj = "obj.coins"
coords = "1_35_93_28_14"

[[spawn]]
obj = "obj.coins"
coords = "1_35_93_29_16"

[[spawn]]
obj = "obj.coins"
coords = "1_35_93_29_22"

[[spawn]]
obj = "obj.coins"
coords = "1_35_93_34_17"

[[spawn]]
obj = "obj.coins"
coords = "1_35_93_34_21"

[[spawn]]
obj = "obj.coins"
coords = "1_35_93_35_14"

[[spawn]]
obj = "obj.coins"
coords = "1_35_93_36_14"

