[[spawn]]
obj = "obj.bones"
coords = "2_38_93_59_26"

[[spawn]]
obj = "obj.bones"
coords = "2_38_93_59_38"

[[spawn]]
obj = "obj.bones"
coords = "2_38_93_62_26"

[[spawn]]
obj = "obj.bones"
coords = "2_38_93_62_37"

[[spawn]]
obj = "obj.bones"
coords = "2_39_93_15_28"

[[spawn]]
obj = "obj.bones"
coords = "2_39_93_58_0"

[[spawn]]
obj = "obj.bones_burnt"
coords = "2_38_93_57_33"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_56_26"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_56_30"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_56_35"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_57_22"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_57_36"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_58_28"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_59_4"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_61_28"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_61_36"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_62_10"

[[spawn]]
obj = "obj.coins"
coords = "1_38_93_62_41"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_25_9"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_27_8"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_28_53"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_29_51"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_29_9"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_30_8"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_34_52"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_35_50"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_37_53"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_51_60"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_53_62"

[[spawn]]
obj = "obj.coins"
coords = "1_39_93_54_61"

[[spawn]]
obj = "obj.coins"
coords = "2_39_93_60_0"

[[spawn]]
obj = "obj.iron_med_helm"
coords = "1_38_93_60_38"

[[spawn]]
obj = "obj.iron_med_helm"
coords = "1_40_93_2_33"

[[spawn]]
obj = "obj.iron_sword"
coords = "1_39_93_1_35"

[[spawn]]
obj = "obj.iron_sword"
coords = "1_40_93_1_31"

