[[spawn]]
obj = "obj.doogleleaves"
coords = "0_49_53_15_7"

[[spawn]]
obj = "obj.doogleleaves"
coords = "0_49_53_16_7"

[[spawn]]
obj = "obj.doogleleaves"
coords = "0_49_53_16_9"

[[spawn]]
obj = "obj.doogleleaves"
coords = "0_49_53_20_9"

[[spawn]]
obj = "obj.doogleleaves"
coords = "0_49_53_21_8"

[[spawn]]
obj = "obj.tray_empty"
coords = "0_52_52_41_50"

