[[spawn]]
obj = "obj.bones"
coords = "0_45_142_20_25"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_22_37"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_23_45"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_24_25"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_24_33"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_25_48"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_26_21"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_27_39"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_27_46"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_29_30"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_31_22"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_31_42"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_33_51"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_34_37"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_35_20"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_36_27"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_36_44"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_39_24"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_39_47"

[[spawn]]
obj = "obj.bones"
coords = "0_45_142_40_35"

