[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_23_42"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_24_40"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_25_37"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_28_40"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_31_39"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_34_36"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_34_40"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_36_43"

[[spawn]]
obj = "obj.big_bones"
coords = "0_30_148_37_38"

