[[spawn]]
obj = "obj.bowl_empty_filliman"
coords = "0_53_52_45_9"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_32_23"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_36_28"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_36_58"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_42_13"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_43_47"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_44_34"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_50_25"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_54_15"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_55_4"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_51_59_56"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_17_35"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_20_38"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_47_49"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_48_47"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_58_30"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_59_30"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_60_49"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_60_50"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_60_60"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_52_60_61"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_36_44"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_40_9"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_42_40"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_43_10"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_43_34"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_49_21"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_49_46"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_50_20"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_53_12"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_53_43"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_56_38"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_57_42"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_58_24"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_59_10"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_53_53_61_49"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_11_48"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_13_33"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_15_15"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_20_36"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_2_39"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_3_46"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_4_26"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_52_6_22"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_10_24"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_13_41"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_14_37"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_15_27"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_16_11"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_16_54"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_17_43"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_18_22"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_21_51"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_22_46"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_24_27"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_27_34"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_38_3"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_38_9"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_3_27"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_46_9"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_4_13"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_5_21"

[[spawn]]
obj = "obj.swamp_tar"
coords = "0_54_53_9_40"

## Barrows

[[spawn]]
obj = "obj.barrows_book_history"
coords = "0_55_51_51_48"

[[spawn]]
obj = "obj.spade"
coords = "0_55_51_51_46"

[[spawn]]
obj = "obj.spade"
coords = "0_55_51_52_48"

## Burgh De Rott

[[spawn]]
obj = "obj.bronze_pickaxe"
coords = "0_55_50_36_36"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_54_50_22_34"

[[spawn]]
obj = "obj.hammer"
coords = "1_54_50_36_42"

[[spawn]]
obj = "obj.net"
coords = "0_54_49_55_53"

[[spawn]]
obj = "obj.pot_empty"
coords = "1_54_50_23_21"

## Canifis Bar Floor

[[spawn]]
obj = "obj.fenk_brain"
coords = "0_54_54_36_18"

## Crombwick Manor

[[spawn]]
obj = "obj.broken_glass"
coords = "1_58_52_3_28"

[[spawn]]
obj = "obj.broken_glass"
coords = "1_58_52_5_32"

[[spawn]]
obj = "obj.broken_glass"
coords = "1_58_52_9_30"

[[spawn]]
obj = "obj.jug_empty"
coords = "1_58_52_6_29"

[[spawn]]
obj = "obj.slepe_book_sister1"
coords = "1_58_52_18_26"

## Darkmeyer

[[spawn]]
obj = "obj.bowl_water"
coords = "0_56_52_37_50"

## Darkmeyer Lower

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_52_40_17"

[[spawn]]
obj = "obj.clay"
coords = "0_56_52_63_42"

[[spawn]]
obj = "obj.lit_candle"
coords = "0_56_52_60_32"

[[spawn]]
obj = "obj.pot_empty"
coords = "0_56_52_62_41"

[[spawn]]
obj = "obj.rope"
coords = "0_56_52_58_9"

[[spawn]]
obj = "obj.tinderbox"
coords = "0_56_52_60_31"

## Darkmeyer Middle

[[spawn]]
obj = "obj.blood_pint"
coords = "0_56_52_12_60"

[[spawn]]
obj = "obj.bowl_mushroom_raw"
coords = "0_56_52_45_53"

[[spawn]]
obj = "obj.bowl_onion"
coords = "0_56_52_45_54"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_52_33_49"

[[spawn]]
obj = "obj.jug_wine"
coords = "0_57_52_15_52"

[[spawn]]
obj = "obj.knife"
coords = "0_56_52_34_59"

[[spawn]]
obj = "obj.needle"
coords = "0_56_52_18_51"

[[spawn]]
obj = "obj.pot_empty"
coords = "0_56_52_58_59"

[[spawn]]
obj = "obj.potato"
coords = "0_56_53_39_3"

[[spawn]]
obj = "obj.raw_rat_meat"
coords = "0_56_52_33_59"

[[spawn]]
obj = "obj.silk"
coords = "0_56_52_18_50"

[[spawn]]
obj = "obj.thread"
coords = "0_56_52_15_51"

## Darkmeyer Upper

[[spawn]]
obj = "obj.blood_pint"
coords = "0_56_51_19_53"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_51_20_56"

[[spawn]]
obj = "obj.bullseye_lantern_unlit"
coords = "0_56_52_29_9"

[[spawn]]
obj = "obj.knife"
coords = "0_56_51_20_57"

[[spawn]]
obj = "obj.knife"
coords = "0_56_51_26_60"

[[spawn]]
obj = "obj.pot_of_not_garlic_butter"
coords = "0_56_51_26_61"

## Darkmeyer Upper House Roofs

[[spawn]]
obj = "obj.blood_pint"
coords = "1_56_52_23_9"

## Meiyerditch

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_49_13_54"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_49_45_62"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_50_20_19"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_50_40_11"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_50_42_54"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_50_42_59"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_50_54_43"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_50_9_19"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_51_13_37"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_51_22_3"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_51_37_18"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_51_43_27"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_51_44_11"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_56_51_51_12"

[[spawn]]
obj = "obj.bucket_empty"
coords = "1_56_50_21_51"

[[spawn]]
obj = "obj.bucket_empty"
coords = "1_56_50_27_46"

[[spawn]]
obj = "obj.bucket_empty"
coords = "1_56_50_38_43"

[[spawn]]
obj = "obj.bucket_empty"
coords = "1_56_50_40_36"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_49_14_54"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_49_32_61"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_50_12_10"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_50_28_14"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_50_28_24"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_50_31_30"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_50_38_23"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_50_44_60"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_17_39"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_20_36"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_36_18"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_43_52"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_43_59"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_43_9"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_49_0"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_49_58"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_50_18"

[[spawn]]
obj = "obj.bucket_water"
coords = "0_56_51_52_51"

[[spawn]]
obj = "obj.bucket_water"
coords = "1_56_50_20_52"

[[spawn]]
obj = "obj.bucket_water"
coords = "1_56_50_55_58"

[[spawn]]
obj = "obj.knife"
coords = "1_56_50_42_48"

## Mortton

[[spawn]]
obj = "obj.smashed_glass"
coords = "0_54_51_25_13"

[[spawn]]
obj = "obj.smashed_glass"
coords = "0_54_51_26_12"

[[spawn]]
obj = "obj.smashed_glass"
coords = "0_54_51_26_15"

[[spawn]]
obj = "obj.vial_empty"
coords = "0_54_51_25_14"

[[spawn]]
obj = "obj.vial_empty"
coords = "0_54_51_25_15"

## Slepe

[[spawn]]
obj = "obj.bones"
coords = "0_58_52_11_16"

[[spawn]]
obj = "obj.bones"
coords = "0_58_52_19_19"

[[spawn]]
obj = "obj.bones"
coords = "0_58_52_24_23"

[[spawn]]
obj = "obj.bones"
coords = "0_58_52_6_21"

[[spawn]]
obj = "obj.bones"
coords = "0_58_52_8_45"

[[spawn]]
obj = "obj.broken_glass"
coords = "0_58_52_22_30"

[[spawn]]
obj = "obj.bronze_dagger"
coords = "0_58_52_18_28"

[[spawn]]
obj = "obj.bucket_empty"
coords = "0_58_52_7_33"

[[spawn]]
obj = "obj.burnt_shrimp"
coords = "0_58_52_55_55"

[[spawn]]
obj = "obj.jug_wine"
coords = "0_58_52_9_25"

[[spawn]]
obj = "obj.knife"
coords = "0_58_52_5_30"

[[spawn]]
obj = "obj.raw_rat_meat"
coords = "0_58_52_16_33"

[[spawn]]
obj = "obj.rotten_food"
coords = "1_58_51_40_33"

[[spawn]]
obj = "obj.slepe_bloody_bracer"
coords = "0_58_51_37_31"

[[spawn]]
obj = "obj.slepe_manuscript_crombwick_deed"
coords = "0_58_52_20_33"

[[spawn]]
obj = "obj.smashed_glass"
coords = "0_58_52_56_54"

[[spawn]]
obj = "obj.vial_empty"
coords = "0_58_52_4_30"

## Slepe Church

[[spawn]]
obj = "obj.slepe_book_sister2"
coords = "2_58_51_22_54"

## Slepe Houses

[[spawn]]
obj = "obj.bowl_garlic"
coords = "0_58_51_7_39"

[[spawn]]
obj = "obj.bowl_water"
coords = "1_57_52_55_3"

[[spawn]]
obj = "obj.bowl_water"
coords = "1_58_52_30_6"

[[spawn]]
obj = "obj.lit_candle"
coords = "0_58_51_3_38"

[[spawn]]
obj = "obj.lit_candle"
coords = "1_57_52_50_11"

[[spawn]]
obj = "obj.lit_candle"
coords = "1_58_52_38_11"

[[spawn]]
obj = "obj.papyrus"
coords = "1_57_52_50_10"

[[spawn]]
obj = "obj.papyrus"
coords = "1_58_52_37_11"

[[spawn]]
obj = "obj.raw_shrimp"
coords = "0_58_51_8_39"

## Slepe Houses End

