[[spawn]]
obj = "obj.bones"
coords = "0_36_146_22_13"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_22_15"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_23_13"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_23_61"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_25_55"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_27_31"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_33_49"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_35_52"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_3_53"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_44_15"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_45_17"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_46_16"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_4_1"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_4_3"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_55_41"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_58_60"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_59_11"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_5_52"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_61_10"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_61_7"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_6_2"

[[spawn]]
obj = "obj.bones"
coords = "0_36_146_7_1"

[[spawn]]
obj = "obj.hammer"
coords = "0_36_146_47_39"

