[[spawn]]
obj = "obj.bones"
coords = "0_52_53_26_34"

[[spawn]]
obj = "obj.bones"
coords = "0_52_53_29_36"

[[spawn]]
obj = "obj.bones"
coords = "0_52_53_33_19"

[[spawn]]
obj = "obj.bones"
coords = "0_52_53_40_19"

[[spawn]]
obj = "obj.bones"
coords = "0_52_53_41_20"

