[[spawn]]
obj = "obj.cocktail_glass_empty"
coords = "1_38_54_51_26"

[[spawn]]
obj = "obj.cocktail_glass_empty"
coords = "1_38_54_57_33"

[[spawn]]
obj = "obj.cocktail_shaker"
coords = "1_38_54_17_54"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_40_59"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_40_62"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_46_54"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_46_62"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_47_55"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_47_61"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_51_55"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_57_59"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_58_51"

[[spawn]]
obj = "obj.king_worm"
coords = "0_37_54_59_52"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_53_13_22"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_53_14_20"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_53_20_18"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_39_60"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_41_58"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_43_56"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_44_63"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_45_55"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_47_62"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_48_56"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_49_52"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_49_56"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_49_59"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_49_60"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_50_55"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_50_61"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_53_53"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_53_63"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_56_58"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_56_61"

[[spawn]]
obj = "obj.swamp_toad"
coords = "0_37_54_60_54"

