[[spawn]]
obj = "obj.seaweed"
coords = "0_46_40_14_43"

[[spawn]]
obj = "obj.seaweed"
coords = "0_46_40_18_40"

[[spawn]]
obj = "obj.seaweed"
coords = "0_46_40_22_42"

[[spawn]]
obj = "obj.seaweed"
coords = "0_46_40_24_47"

[[spawn]]
obj = "obj.seaweed"
coords = "0_46_40_26_41"

[[spawn]]
obj = "obj.seaweed"
coords = "0_46_40_27_45"

