[[spawn]]
obj = "obj.logs"
coords = "0_48_48_28_22"

[[spawn]]
obj = "obj.logs"
coords = "0_48_48_29_24"

## Tutorial Island Underground

[[spawn]]
obj = "obj.bones"
coords = "0_48_148_34_42"

[[spawn]]
obj = "obj.bones"
coords = "0_48_148_34_46"

[[spawn]]
obj = "obj.bones"
coords = "0_48_148_36_47"

[[spawn]]
obj = "obj.bones"
coords = "0_48_148_36_48"

## Tutorial Island Underground End

