[[spawn]]
obj = "obj.cup_of_tea"
coords = "1_40_48_33_31"

[[spawn]]
obj = "obj.jug_water"
coords = "0_40_48_8_30"

## Wizards' Guild

[[spawn]]
obj = "obj.vial_empty"
coords = "2_40_48_27_18"

[[spawn]]
obj = "obj.vial_empty"
coords = "2_40_48_28_18"

## Yanille Dungeon

[[spawn]]
obj = "obj.herring"
coords = "0_40_148_3_39"

[[spawn]]
obj = "obj.knife"
coords = "0_40_148_7_54"

## Yanille Watchtower Bottom

[[spawn]]
obj = "obj.lit_candle"
coords = "0_39_48_51_42"

## Yanille Watchtower Bottom End

