[gamevals.dbtable]
runecrafting_runes=65517
runecrafting_altars=65516
runecrafting_tiara=65515

[gamevals.dbrow]
runecrafting_rune_sunfire=65173
runecrafting_rune_blood_dark=65172
runecrafting_rune_aether=65171
runecrafting_altar_sunfire=65170
runecrafting_altar_blood_kourend=65169
runecrafting_altar_ourania=65168
runecrafting_rune_air=65167
runecrafting_rune_mind=65166
runecrafting_rune_water=65165
runecrafting_rune_earth=65164
runecrafting_rune_fire=65163
runecrafting_rune_body=65162
runecrafting_rune_cosmic=65161
runecrafting_rune_chaos=65160
runecrafting_rune_nature=65159
runecrafting_rune_law=65158
runecrafting_rune_death=65157
runecrafting_rune_wrath=65156
runecrafting_rune_soul=65155
runecrafting_rune_blood=65154
runecrafting_rune_astral=65153
runecrafting_altar_astral=65152
runecrafting_altar_blood=65151
runecrafting_altar_soul=65150
runecrafting_altar_wrath=65149
runecrafting_altar_death=65148
runecrafting_altar_law=65147
runecrafting_altar_nature=65146
runecrafting_altar_chaos=65145
runecrafting_altar_cosmic=65144
runecrafting_altar_body=65143
runecrafting_altar_fire=65142
runecrafting_altar_earth=65141
runecrafting_altar_water=65140
runecrafting_altar_mind=65139
runecrafting_altar_air=65138
runecrafting_tiara_wrath=65137
runecrafting_tiara_death=65136
runecrafting_tiara_law=65135
runecrafting_tiara_nature=65134
runecrafting_tiara_chaos=65133
runecrafting_tiara_cosmic=65132
runecrafting_tiara_body=65131
runecrafting_tiara_fire=65130
runecrafting_tiara_earth=65129
runecrafting_tiara_water=65128
runecrafting_tiara_mind=65127
runecrafting_tiara_air=65126

[gamevals.varbit]
blood_essence_charges=65529
binding_necklace_charges=65528
cordelia_pouch_repair_unlocked=65099

[gamevals.varp]
rcu_pouch_essence_type_small=65481
rcu_pouch_essence_type_med=65482
rcu_pouch_essence_type_large=65483
rcu_pouch_essence_type_giant=65484
rcu_pouch_essence_type_colossal=65485

[gamevals.queue]
runecraft_magic_imbue_expire=65526