CREATE TABLE IF NOT EXISTS realms (
    realm_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    login_message TEXT,
    login_broadcast TEXT,
    spawn_coord TEXT NOT NULL DEFAULT '0_50_50_21_18',
    respawn_coord TEXT NOT NULL DEFAULT '0_50_50_21_18',
    dev_mode INTEGER NOT NULL DEFAULT 0, -- when 1: LOGIN_OK always modlevel.owner (gates still use accounts.rights)
    require_registration INTEGER NOT NULL DEFAULT 1,
    auto_assign_display_names INTEGER NOT NULL DEFAULT 0,
    player_xp_rate_in_hundreds INTEGER NOT NULL DEFAULT 100,
    global_xp_rate_in_hundreds INTEGER NOT NULL DEFAULT 100
);

INSERT INTO realms (
    realm_id, name, description, login_message, login_broadcast, spawn_coord, respawn_coord,
    dev_mode, require_registration, auto_assign_display_names,
    player_xp_rate_in_hundreds, global_xp_rate_in_hundreds
)
VALUES (
    255, 'development', 'Development realm', 'Welcome to OpenRune.', NULL,
    '0_50_50_21_18', '0_50_50_21_18',
    1, 0, 1,
    150, 100
)
ON CONFLICT (realm_id) DO NOTHING;
