CREATE TABLE IF NOT EXISTS worlds (
    world_id INTEGER PRIMARY KEY,
    flags TEXT NOT NULL DEFAULT '',
    host TEXT NOT NULL,
    activity TEXT NOT NULL,
    location INTEGER NOT NULL DEFAULT 0,
    population INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled INTEGER NOT NULL DEFAULT 1,
    max_players INTEGER NULL,
    world_key_sha256 BYTEA NULL,
    realm_id INTEGER NOT NULL REFERENCES realms (realm_id),
    login_restrictions_enabled INTEGER NOT NULL DEFAULT 0,
    login_min_total_level INTEGER NOT NULL DEFAULT 0,
    login_min_rights_token TEXT NULL,
    login_gate_min_level_enabled INTEGER NOT NULL DEFAULT 0,
    login_gate_rights_enabled INTEGER NOT NULL DEFAULT 0,
    login_gate_whitelist_enabled INTEGER NOT NULL DEFAULT 0
);

INSERT INTO worlds (
    world_id, flags, host, activity, location, population, sort_order, enabled,
    max_players, world_key_sha256, realm_id,
    login_restrictions_enabled, login_min_total_level, login_min_rights_token,
    login_gate_min_level_enabled, login_gate_rights_enabled, login_gate_whitelist_enabled
)
VALUES (
    255, 'MEMBERS', '127.0.0.1', 'OpenRune', 0, 0, 0, 1,
    NULL, NULL, 255,
    0, 0, NULL,
    0, 0, 0
)
ON CONFLICT (world_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS world_login_whitelist (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    world_id INTEGER NOT NULL REFERENCES worlds (world_id) ON DELETE CASCADE,
    account_name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_world_login_whitelist_world_account_lower ON world_login_whitelist (world_id, lower(account_name));
CREATE INDEX IF NOT EXISTS idx_world_login_whitelist_world ON world_login_whitelist (world_id);

UPDATE worlds w
SET
    login_gate_min_level_enabled = CASE WHEN w.login_min_total_level > 0 THEN 1 ELSE 0 END,
    login_gate_rights_enabled =
        CASE
            WHEN w.login_min_rights_token IS NOT NULL AND trim(w.login_min_rights_token) <> '' THEN 1
            ELSE 0
        END,
    login_gate_whitelist_enabled =
        CASE
            WHEN EXISTS (SELECT 1 FROM world_login_whitelist wl WHERE wl.world_id = w.world_id) THEN 1
            ELSE 0
        END
WHERE
    w.login_restrictions_enabled <> 0
    AND (
        w.login_gate_min_level_enabled = 0
        AND w.login_gate_rights_enabled = 0
        AND w.login_gate_whitelist_enabled = 0
    );
