CREATE TABLE IF NOT EXISTS account_characters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL,
    display_name TEXT UNIQUE,
    members BOOLEAN NOT NULL DEFAULT FALSE,
    world_id INTEGER,
    x INTEGER NOT NULL DEFAULT 3200,
    z INTEGER NOT NULL DEFAULT 3200,
    level INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    last_logout TIMESTAMP,
    muted_until TIMESTAMP,
    banned_until TIMESTAMP,
    run_energy INTEGER NOT NULL DEFAULT 10000,
    xp_rate_in_hundreds INTEGER NOT NULL DEFAULT 100,
    online_central_world_id INTEGER NULL,
    online_session_heartbeat TIMESTAMP NULL,
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE,
    FOREIGN KEY (world_id) REFERENCES worlds (world_id)
);

CREATE INDEX IF NOT EXISTS idx_account_characters_account_id ON account_characters (account_id);

-- NOTIFY when `account_characters.muted_until` changes (Central LISTEN → world-link OP_SERVER_MUTE_UPDATE).
CREATE OR REPLACE FUNCTION account_characters_notify_mute_fn() RETURNS trigger AS $$
DECLARE
    epoch_ms bigint;
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.muted_until IS NOT DISTINCT FROM OLD.muted_until THEN
        RETURN NEW;
    END IF;
    IF TG_OP = 'INSERT' AND NEW.muted_until IS NULL THEN
        RETURN NEW;
    END IF;
    IF NEW.muted_until IS NULL THEN
        epoch_ms := 0;
    ELSE
        epoch_ms := (EXTRACT(EPOCH FROM NEW.muted_until) * 1000)::bigint;
    END IF;
    PERFORM pg_notify(
        'character_mute_events',
        json_build_object(
            'account_id', NEW.account_id,
            'character_id', NEW.id,
            'muted_until_epoch_millis', epoch_ms::text
        )::text
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER account_characters_notify_mute
AFTER INSERT OR UPDATE OF muted_until ON account_characters
FOR EACH ROW
EXECUTE PROCEDURE account_characters_notify_mute_fn();

-- Reserved display names after a rename (others cannot take the name until release_at).
-- Case-sensitive held_name matches account_characters.display_name uniqueness rules.
CREATE TABLE IF NOT EXISTS display_name_holds (
    held_name TEXT PRIMARY KEY,
    release_at TIMESTAMPTZ NOT NULL,
    source_character_id INTEGER NULL REFERENCES account_characters (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_display_name_holds_release_at ON display_name_holds (release_at);
