id = "Ancient Wizard Drops"
npcs = ["npc.trail_zaros_wizard", "npc.trail_zaros_range", "npc.trail_zaros_melee"]

[main]
total = 50
name = "Ancient Wizard Drops"

[[main.entries]]
weight = 1
obj = "obj.fire_battlestaff"
count = 1

[[main.entries]]
weight = 1
obj = "obj.staff_of_fire"
count = 1

[[main.entries]]
weight = 5
obj = "obj.airrune"
count = "5..24"

[[main.entries]]
weight = 5
obj = "obj.firerune"
count = "5..24"

[[main.entries]]
weight = 5
obj = "obj.deathrune"
count = "5..24"

[[main.entries]]
weight = 5
obj = "obj.xbows_crossbow_bolts_runite"
count = "1..5"

[[main.entries]]
weight = 10
obj = "obj.coins"
count = "50..249"

[[main.entries]]
weight = 2
obj = "obj.4doseprayerrestore"
count = 1

[[main.entries]]
weight = 7
obj = "obj.cert_blankrune_high"
count = 25

[[main.entries]]
weight = 1
obj = "obj.xbows_crossbow_unstrung_runite"
count = 1

[[main.entries]]
weight = 5
shared = "herb"

[[main.entries]]
weight = 3
nothing = true

[[tertiary]]
numerator = 1
denominator = 3
obj = "obj.looting_bag"
count = 1
should_drop_looting_bag = true


# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (3 weight)
