id = "Basilisk Youngling Drops"
npcs = ["npc.vikingexile_youngling"]

[[guaranteed]]
obj = "obj.vikingexile_letter"
count = 1

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_baby_basilisk_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"
