id = "Battle mage Drops"
npcs = ["npc.zamorak_mage", "npc.saradomin_mage", "npc.guthix_mage"]

[[tertiary]]
numerator = 1
denominator = 3
obj = "obj.looting_bag"
count = 1
should_drop_looting_bag = true
