id = "Bloodthirsty Crawler Drops"
npcs = ["npc.league_superior_cave_crawler"]

[main]
total = 128
name = "Bloodthirsty Crawler Drops"

[[main.entries]]
weight = 1
obj = "obj.bronze_armoured_boots"
count = 1

[[main.entries]]
weight = 6
obj = "obj.naturerune"
count = "3..4"

[[main.entries]]
weight = 5
obj = "obj.firerune"
count = 12

[[main.entries]]
weight = 2
obj = "obj.earthrune"
count = 9

[[main.entries]]
weight = 13
obj = "obj.vial_water"
count = 1

[[main.entries]]
weight = 5
obj = "obj.white_berries"
count = 1

[[main.entries]]
weight = 2
obj = "obj.unicorn_horn_dust"
count = 1

[[main.entries]]
weight = 1
obj = "obj.eye_of_newt"
count = 1

[[main.entries]]
weight = 1
obj = "obj.red_spiders_eggs"
count = 1

[[main.entries]]
weight = 1
obj = "obj.limpwurt_root"
count = 1

[[main.entries]]
weight = 1
obj = "obj.snape_grass"
count = 1

[[main.entries]]
weight = 5
obj = "obj.coins"
count = 3

[[main.entries]]
weight = 3
obj = "obj.coins"
count = 8

[[main.entries]]
weight = 3
obj = "obj.coins"
count = 29

[[main.entries]]
weight = 1
obj = "obj.coins"
count = 10

[[main.entries]]
weight = 29
nothing = true

[[main.entries]]
weight = 22
shared = "herb"

[[main.entries]]
weight = 1
shared = "gem"

[[main.entries]]
weight = 26
nothing = true

[[main.separate_rolls]]
numerator = 5
denominator = 40

[[main.separate_rolls.entries]]
weight = 5
obj = "obj.cert_raw_lobster"
count = "60..80"

[[main.separate_rolls.entries]]
weight = 5
obj = "obj.cert_unicorn_horn"
count = "60..150"

[[main.separate_rolls]]
numerator = 10
denominator = 40

[[main.separate_rolls.entries]]
weight = 10
obj = "obj.cert_snape_grass"
count = "60..150"

[[main.separate_rolls.entries]]
weight = 10
obj = "obj.irit_seed"
count = "10..15"

[[main.separate_rolls.entries]]
weight = 10
obj = "obj.cert_limpwurt_root"
count = "60..150"


# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (26 weight)
