id = "Bunny Drops"
npcs = ["npc.viking_bunny_1", "npc.viking_bunny_2"]

[[guaranteed]]
obj = "obj.raw_rabbit"
count = 1

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_rabbit_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"
