id = "Cyclops (God Wars Dungeon) Drops"
npcs = ["npc.godwars_ancient_cyclops", "npc.godwars_ancient_cyclops2"]

[main]
total = 100
name = "Cyclops (God Wars Dungeon) Drops"

[[main.entries]]
weight = 16
obj = "obj.black_knife"
count = "4..13"

[[main.entries]]
weight = 2
obj = "obj.steel_chainbody"
count = 1

[[main.entries]]
weight = 2
obj = "obj.iron_2h_sword"
count = 1

[[main.entries]]
weight = 2
obj = "obj.iron_chainbody"
count = 1

[[main.entries]]
weight = 2
obj = "obj.steel_dagger"
count = 1

[[main.entries]]
weight = 2
obj = "obj.steel_mace"
count = 1

[[main.entries]]
weight = 2
obj = "obj.steel_sword"
count = 1

[[main.entries]]
weight = 2
obj = "obj.steel_battleaxe"
count = 1

[[main.entries]]
weight = 2
obj = "obj.steel_2h_sword"
count = 1

[[main.entries]]
weight = 2
obj = "obj.steel_longsword"
count = 1

[[main.entries]]
weight = 2
obj = "obj.steel_med_helm"
count = 1

[[main.entries]]
weight = 1
obj = "obj.black_2h_sword"
count = 1

[[main.entries]]
weight = 1
obj = "obj.mithril_dagger"
count = 1

[[main.entries]]
weight = 1
obj = "obj.mithril_longsword"
count = 1

[[main.entries]]
weight = 1
obj = "obj.adamant_mace"
count = 1

[[main.entries]]
weight = 1
obj = "obj.black_sword"
count = 1

[[main.entries]]
weight = 1
obj = "obj.black_longsword"
count = 1

[[main.entries]]
weight = 1
obj = "obj.black_dagger"
count = 1

[[main.entries]]
weight = 1
obj = "obj.adamant_2h_sword"
count = 1

[[main.entries]]
weight = 40
obj = "obj.coins"
count = "3..102"

[[main.entries]]
weight = 10
obj = "obj.coins"
count = "5..204"

[[main.entries]]
weight = 3
shared = "herb"

[[main.entries]]
weight = 2
shared = "gem"

[[main.entries]]
weight = 1
nothing = true

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1

[[tertiary]]
numerator = 1
denominator = 486
obj = "obj.trail_clue_hard_map001"
count = 1
clue_scroll_box = true


# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (1 weight)
