id = "Dagannoth Supreme Drops"
npcs = ["npc.dagcave_ranged_boss"]
brimstone_key_roll = true

[[guaranteed]]
obj = "obj.dagganoth_hide"
count = 1

[main]
total = 128
name = "Dagannoth Supreme Drops"

[[main.entries]]
weight = 10
obj = "obj.mithril_knife"
count = "25..50"

[[main.entries]]
weight = 7
obj = "obj.red_dragon_vambraces"
count = 1

[[main.entries]]
weight = 5
obj = "obj.rune_thrownaxe"
count = "5..10"

[[main.entries]]
weight = 5
obj = "obj.adamant_dart"
count = "10..25"

[[main.entries]]
weight = 5
obj = "obj.iron_knife"
count = "200..500"

[[main.entries]]
weight = 5
obj = "obj.steel_knife"
count = "50..150"

[[main.entries]]
weight = 1
obj = "obj.viking_sword"
count = 1

[[main.entries]]
weight = 1
obj = "obj.viking_shield"
count = 1

[[main.entries]]
weight = 1
obj = "obj.viking_helmet"
count = 1

[[main.entries]]
weight = 1
obj = "obj.daganoth_cave_magic_shortbow"
count = 1

[[main.entries]]
weight = 1
obj = "obj.dragon_axe"
count = 1

[[main.entries]]
weight = 1
obj = "obj.viking_helmet_range"
count = 1

[[main.entries]]
weight = 1
obj = "obj.dagganoth_ranged_body"
count = 1

[[main.entries]]
weight = 1
obj = "obj.dagganoth_ranged_legs"
count = 1

[[main.entries]]
weight = 1
obj = "obj.ranger_ring"
count = 1

[[main.entries]]
weight = 5
obj = "obj.steel_arrow"
count = "50..250"

[[main.entries]]
weight = 5
obj = "obj.xbows_crossbow_bolts_runite"
count = "2..12"

[[main.entries]]
weight = 4
obj = "obj.iron_arrow"
count = "200..700"

[[main.entries]]
weight = 10
obj = "obj.coins"
count = "500..1110"

[[main.entries]]
weight = 6
obj = "obj.bigoysterpearls"
count = 1

[[main.entries]]
weight = 5
obj = "obj.opal_bolttips"
count = "10..30"

[[main.entries]]
weight = 5
obj = "obj.shark"
count = 5

[[main.entries]]
weight = 5
obj = "obj.cert_yew_logs"
count = "50..150"

[[main.entries]]
weight = 5
obj = "obj.unidentified_ranarr"
count = 1

[[main.entries]]
weight = 3
obj = "obj.cert_maple_logs"
count = "15..65"

[[main.entries]]
weight = 2
obj = "obj.xbows_crossbow_limbs_runite"
count = 1

[[main.entries]]
weight = 1
obj = "obj.feather"
count = "250..500"

[[main.entries]]
weight = 8
shared = "rareDrop"

[[main.entries]]
weight = 10
shared = "gem"

[[main.entries]]
weight = 7
shared = "rareSeed"

[[main.entries]]
weight = 1
nothing = true

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_dagganoth_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"

[[tertiary]]
numerator = 1
denominator = 20
obj = "obj.arceuus_corpse_dagannoth"
count = 1

[[tertiary]]
numerator = 1
denominator = 5000
obj = "obj.supremepet"
count = 1

[[tertiary]]
numerator = 1
denominator = 39
obj = "obj.trail_clue_hard_map001"
count = 1
clue_scroll_box = true

[[tertiary]]
numerator = 1
denominator = 712
obj = "obj.trail_elite_emote_exp1"
count = 1
clue_scroll_box = true


# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (1 weight)
