id = "Derwen Drops"
npcs = ["npc.ma2_boss_guthix_spawning", "npc.ma2_boss_guthix"]

[[guaranteed]]
obj = "obj.ma2_guthix_heart"
count = 1

[[tertiary]]
numerator = 1
denominator = 3
obj = "obj.looting_bag"
count = 1
should_drop_looting_bag = true
