id = "Donny the lad Drops"
npcs = ["npc.donny_the_lad"]

[main]
total = 128
name = "Donny the lad Drops"

[[main.entries]]
weight = 1
obj = "obj.steel_longsword"
count = 1

[[main.entries]]
weight = 1
obj = "obj.steel_full_helm"
count = 1

[[main.entries]]
weight = 4
obj = "obj.lawrune"
count = 2

[[main.entries]]
weight = 4
obj = "obj.naturerune"
count = 4

[[main.entries]]
weight = 3
obj = "obj.bodyrune"
count = 12

[[main.entries]]
weight = 3
obj = "obj.chaosrune"
count = 3

[[main.entries]]
weight = 3
obj = "obj.waterrune"
count = 30

[[main.entries]]
weight = 1
obj = "obj.mindrune"
count = 5

[[main.entries]]
weight = 30
obj = "obj.coins"
count = 48

[[main.entries]]
weight = 18
obj = "obj.coins"
count = 15

[[main.entries]]
weight = 11
obj = "obj.coins"
count = 8

[[main.entries]]
weight = 10
obj = "obj.coins"
count = 70

[[main.entries]]
weight = 5
obj = "obj.coins"
count = 5

[[main.entries]]
weight = 2
obj = "obj.coins"
count = 150

[[main.entries]]
weight = 11
obj = "obj.silver_ore"
count = 1

[[main.entries]]
weight = 2
nothing = true

[[main.entries]]
weight = 2
obj = "obj.cert_swordfish"
count = 5

[[main.entries]]
weight = 15
shared = "herb"

[[main.entries]]
weight = 2
shared = "gem"

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.looting_bag"
count = 1
should_drop_looting_bag = true
