id = "Enraged Boar Drops"
npcs = ["npc.gim_boar"]

[[guaranteed]]
obj = "obj.raw_boar_meat"
count = 1

[[tertiary]]
numerator = 1
denominator = 128
obj = "obj.trail_clue_beginner"
count = 1
clue_scroll_box = true
