id = "Gorad Drops"
npcs = ["npc.gorad"]

[[tertiary]]
numerator = 1
denominator = 1
obj = "obj.ogretooth"
count = 1
quest = "quest_watchtowerquest"
quest_mode = "during"

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_ogre_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"

[[tertiary]]
numerator = 1
denominator = 30
obj = "obj.arceuus_corpse_ogre"
count = 1

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1
