id = "Knight of Saradomin Drops"
npcs = ["npc.godwars_saradomin_knight_1", "npc.godwars_saradomin_knight_2"]

[[tertiary]]
numerator = 1
denominator = 3
obj = "obj.looting_bag"
count = 1
should_drop_looting_bag = true

[[tertiary]]
numerator = 1
denominator = 121
obj = "obj.trail_clue_hard_map001"
count = 1
clue_scroll_box = true
exclude_ring_of_wealth = true

[[tertiary]]
numerator = 1
denominator = 64
obj = "obj.trail_clue_hard_map001"
count = 1
clue_scroll_box = true
require_ring_of_wealth = true
require_wilderness = true
