id = "Malevolent Mage Drops"
npcs = ["npc.superior_infernal_mage"]

[main]
total = 128
name = "Malevolent Mage Drops"

[[main.entries]]
weight = 8
obj = "obj.plainstaff"
count = 1

[[main.entries]]
weight = 1
obj = "obj.staff_of_fire"
count = 1

[[main.entries]]
weight = 6
obj = "obj.earthrune"
count = 10

[[main.entries]]
weight = 6
obj = "obj.firerune"
count = 10

[[main.entries]]
weight = 4
obj = "obj.earthrune"
count = 36

[[main.entries]]
weight = 3
obj = "obj.airrune"
count = 10

[[main.entries]]
weight = 3
obj = "obj.waterrune"
count = 10

[[main.entries]]
weight = 2
obj = "obj.airrune"
count = 18

[[main.entries]]
weight = 2
obj = "obj.waterrune"
count = 18

[[main.entries]]
weight = 2
obj = "obj.earthrune"
count = 18

[[main.entries]]
weight = 2
obj = "obj.firerune"
count = 18

[[main.entries]]
weight = 2
obj = "obj.mindrune"
count = 18

[[main.entries]]
weight = 2
obj = "obj.bodyrune"
count = 18

[[main.entries]]
weight = 2
obj = "obj.bloodrune"
count = 4

[[main.entries]]
weight = 18
obj = "obj.deathrune"
count = 7

[[main.entries]]
weight = 19
obj = "obj.coins"
count = 1

[[main.entries]]
weight = 14
obj = "obj.coins"
count = 2

[[main.entries]]
weight = 8
obj = "obj.coins"
count = 4

[[main.entries]]
weight = 3
obj = "obj.coins"
count = 29

[[main.entries]]
weight = 21
nothing = true

[[main.separate_rolls]]
numerator = 1
denominator = 512

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.mystic_boots_dark"
count = 1

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.mystic_hat_dark"
count = 1

[[main.separate_rolls]]
numerator = 1
denominator = 1000

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.lava_battlestaff"
count = 1


# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (21 weight)
