id = "Mind Golem Drops"
npcs = ["npc.camdozaal_golem_mind", "npc.camdozaal_golem_mind_rock"]

[main]
total = 52
name = "Mind Golem Drops"

[[main.entries]]
weight = 6
obj = "obj.clay"
count = "2..3"

[[main.entries]]
weight = 6
obj = "obj.copper_ore"
count = "2..3"

[[main.entries]]
weight = 6
obj = "obj.tin_ore"
count = "2..3"

[[main.entries]]
weight = 6
obj = "obj.iron_ore"
count = "1..2"

[[main.entries]]
weight = 6
obj = "obj.cert_blankrune"
count = "3..5"

[[main.entries]]
weight = 1
obj = "obj.cert_blankrune"
count = 1

[[main.entries]]
weight = 8
obj = "obj.mindrune"
count = "5..10"

[[main.entries]]
weight = 6
obj = "obj.mindrune"
count = 1

[[main.entries]]
weight = 4
obj = "obj.uncut_sapphire"
count = 1

[[main.entries]]
weight = 2
obj = "obj.uncut_emerald"
count = 1

[[main.entries]]
weight = 1
obj = "obj.uncut_ruby"
count = 1

[[tertiary]]
numerator = 2
denominator = 15
obj = "obj.camdozaal_barronite_shard"
count = "8..16"

[[tertiary]]
numerator = 2
denominator = 15
obj = "obj.camdozaal_golem_core_mind"
count = 1

[[tertiary]]
numerator = 1
denominator = 500
obj = "obj.barronite_mace_3"
count = 1

[[tertiary]]
numerator = 1
denominator = 50
obj = "obj.trail_clue_beginner"
count = 1
