id = "Moss Guardian Drops"
npcs = ["npc.roving_mossgiant"]

[[guaranteed]]
obj = "obj.roving_old_consecration_seed"
count = 1
quest = "quest_rovingelves"
quest_mode = "during"

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1
