id = "Strange creature (Shadows of Custodia) Drops"
npcs = ["npc.soc_quest_juvenile"]

[main]
total = 160
name = "Strange creature (Shadows of Custodia) Drops"

[[main.entries]]
weight = 20
obj = "obj.mcannonball"
count = "10..15"

[[main.entries]]
weight = 20
obj = "obj.airrune"
count = 100

[[main.entries]]
weight = 20
obj = "obj.firerune"
count = 50

[[main.entries]]
weight = 12
obj = "obj.rune_arrow"
count = "5..20"

[[main.entries]]
weight = 10
obj = "obj.deathrune"
count = "10..26"

[[main.entries]]
weight = 12
obj = "obj.cert_blankrune_high"
count = 15

[[main.entries]]
weight = 11
obj = "obj.custodian_broken_antler"
count = 1

[[main.entries]]
weight = 8
obj = "obj.swordfish"
count = "2..3"

[[main.entries]]
weight = 4
obj = "obj.raw_beef"
count = 1

[[main.entries]]
weight = 20
obj = "obj.coins"
count = "400..750"

[[main.entries]]
weight = 16
obj = "obj.adamant_scimitar"
count = 1

[[main.entries]]
weight = 1
shared = "rareDrop"

[[main.entries]]
weight = 6
shared = "gem"

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1
