id = "Tower Archer South (level 49)"
npcs = ["npc.guild_towerarcher3"]

[main]
total = 100
name = "Tower Archer South (level 49)"

[[main.entries]]
weight = 10
obj = "obj.mithril_arrow"
count = 1

[[main.entries]]
weight = 90
nothing = true


# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (90 weight)
