id = "Zombie pirate (Braindeath Island) Drops"
npcs = ["npc.deal_zombie_pirates_1", "npc.deal_zombie_pirates_2", "npc.deal_zombie_pirates_3", "npc.deal_zombie_pirates_4", "npc.deal_zombie_pirates_5", "npc.deal_zombie_pirates_6"]

[main]
total = 128
name = "Zombie pirate (Braindeath Island) Drops"

[[main.entries]]
weight = 3
obj = "obj.steel_scimitar"
count = 1

[[main.entries]]
weight = 2
obj = "obj.iron_dagger"
count = 1

[[main.entries]]
weight = 3
obj = "obj.bolt"
count = "2..12"

[[main.entries]]
weight = 3
obj = "obj.airrune"
count = 3

[[main.entries]]
weight = 3
obj = "obj.cosmicrune"
count = 2

[[main.entries]]
weight = 2
obj = "obj.bodyrune"
count = 3

[[main.entries]]
weight = 1
obj = "obj.waterrune"
count = 17

[[main.entries]]
weight = 1
obj = "obj.chaosrune"
count = 4

[[main.entries]]
weight = 21
obj = "obj.coins"
count = 18

[[main.entries]]
weight = 10
obj = "obj.coins"
count = 10

[[main.entries]]
weight = 8
obj = "obj.coins"
count = 26

[[main.entries]]
weight = 6
obj = "obj.coins"
count = 35

[[main.entries]]
weight = 2
obj = "obj.coins"
count = 40

[[main.entries]]
weight = 21
obj = "obj.fishing_bait"
count = 7

[[main.entries]]
weight = 5
obj = "obj.fishing_bait"
count = 10

[[main.entries]]
weight = 3
obj = "obj.deal_karamthulhu"
count = 1

[[main.entries]]
weight = 1
obj = "obj.iron_ore"
count = 1

[[main.entries]]
weight = 1
obj = "obj.eye_patch"
count = 1

[[main.entries]]
weight = 1
obj = "obj.deal_rusty_scimitar"
count = 1

[[main.entries]]
weight = 30
shared = "herb"

[[main.entries]]
weight = 1
shared = "gem"

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_zombie_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"

[[tertiary]]
numerator = 1
denominator = 5000
obj = "obj.champions_challenge_zombie"
count = 1
