[[inventory]]
isServerOnly = true
id = "inv.arheinstore"
name = "Arhein's General Goods"

scope = "Shared"
stack = "Always"

sellMultiplier = 1300
buyMultiplier = 400
delta = 30

size = 11

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.bucket_empty"
count = 10
restockCycles = 50

[[inventory.stock]]
obj = "obj.pack_bucket"
count = 15
restockCycles = 10

[[inventory.stock]]
obj = "obj.bronze_pickaxe"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.bowl_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.cake_tin"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.tinderbox"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.chisel"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.hammer"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.rope"
count = 2
restockCycles = 300

[[inventory.stock]]
obj = "obj.pot_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.knife"
count = 2
restockCycles = 100

