[[inventory]]
isServerOnly = true
id = "inv.bedabincampshop"
name = "Bedabin Village Bartering"

scope = "Shared"
stack = "Always"

sellMultiplier = 1200
buyMultiplier = 800
delta = 30

size = 7

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.water_skin4"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.water_skin0"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.jug_water"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.bowl_water"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.bucket_water"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.knife"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.hammer"
count = 5
restockCycles = 100

