[[inventory]]
isServerOnly = true
id = "inv.craftingshop2"
name = "Dommik's Crafting Store."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 650
delta = 20

size = 11

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.chisel"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.ring_mould"
count = 4
restockCycles = 100

[[inventory.stock]]
obj = "obj.necklace_mould"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.amulet_mould"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.needle"
count = 3
restockCycles = 100

[[inventory.stock]]
obj = "obj.thread"
count = 100
restockCycles = 5

[[inventory.stock]]
obj = "obj.holy_symbol_mould"
count = 3
restockCycles = 100

[[inventory.stock]]
obj = "obj.sickle_mould"
count = 6
restockCycles = 15

[[inventory.stock]]
obj = "obj.tiara_mould"
count = 10
restockCycles = 10

[[inventory.stock]]
obj = "obj.xbows_silver_bolt_mould"
count = 10
restockCycles = 10

[[inventory.stock]]
obj = "obj.jewl_bracelet_mould"
count = 5
restockCycles = 100

