[[inventory]]
isServerOnly = true
id = "inv.dorgeshuun_weapon_shop"
name = "Nardok's Bone Weapons"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 20

size = 6

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.cave_goblin_bone_club"
count = 10
restockCycles = 20

[[inventory.stock]]
obj = "obj.cave_goblin_bone_spear"
count = 10
restockCycles = 20

[[inventory.stock]]
obj = "obj.dttd_bone_dagger"
count = 5
restockCycles = 20

[[inventory.stock]]
obj = "obj.dttd_bone_crossbow"
count = 5
restockCycles = 20

[[inventory.stock]]
obj = "obj.dttd_bone_crossbow_bolt"
count = 1000
restockCycles = 20

[[inventory.stock]]
obj = "obj.pack_bone_bolt"
count = 80
restockCycles = 10

