[[inventory]]
isServerOnly = true
id = "inv.fishingguild"
name = "Fishing Guild Shop."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 700
delta = 10

size = 22

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.net"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.big_net"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.fishing_rod"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.fly_fishing_rod"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.harpoon"
count = 2
restockCycles = 400

[[inventory.stock]]
obj = "obj.lobster_pot"
count = 2
restockCycles = 400

[[inventory.stock]]
obj = "obj.fishing_bait"
count = 2000
restockCycles = 1

[[inventory.stock]]
obj = "obj.pack_fishing_bait"
count = 150
restockCycles = 5

[[inventory.stock]]
obj = "obj.feather"
count = 1500
restockCycles = 1

[[inventory.stock]]
obj = "obj.pack_feather"
count = 150
restockCycles = 2

[[inventory.stock]]
obj = "obj.raw_cod"
count = 0
restockCycles = 300

[[inventory.stock]]
obj = "obj.raw_mackerel"
count = 0
restockCycles = 600

[[inventory.stock]]
obj = "obj.raw_bass"
count = 0
restockCycles = 900

[[inventory.stock]]
obj = "obj.raw_tuna"
count = 0
restockCycles = 2300

[[inventory.stock]]
obj = "obj.raw_lobster"
count = 0
restockCycles = 2600

[[inventory.stock]]
obj = "obj.raw_swordfish"
count = 0
restockCycles = 2900

[[inventory.stock]]
obj = "obj.cod"
count = 0
restockCycles = 300

[[inventory.stock]]
obj = "obj.mackerel"
count = 0
restockCycles = 600

[[inventory.stock]]
obj = "obj.bass"
count = 0
restockCycles = 900

[[inventory.stock]]
obj = "obj.tuna"
count = 0
restockCycles = 2300

[[inventory.stock]]
obj = "obj.lobster"
count = 0
restockCycles = 2600

[[inventory.stock]]
obj = "obj.swordfish"
count = 0
restockCycles = 2900

