[[inventory]]
isServerOnly = true
id = "inv.frisd_oreshop"
name = "Ore store"

scope = "Shared"
stack = "Always"

sellMultiplier = 1100
buyMultiplier = 700
delta = 30

size = 8

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.copper_ore"
count = 20
restockCycles = 10

[[inventory.stock]]
obj = "obj.tin_ore"
count = 10
restockCycles = 10

[[inventory.stock]]
obj = "obj.iron_ore"
count = 10
restockCycles = 10

[[inventory.stock]]
obj = "obj.silver_ore"
count = 5
restockCycles = 10

[[inventory.stock]]
obj = "obj.coal"
count = 10
restockCycles = 10

[[inventory.stock]]
obj = "obj.gold_ore"
count = 5
restockCycles = 10

[[inventory.stock]]
obj = "obj.mithril_ore"
count = 0
restockCycles = 10

[[inventory.stock]]
obj = "obj.adamantite_ore"
count = 0
restockCycles = 10

