[[inventory]]
isServerOnly = true
id = "inv.hundred_foodchest2"
name = "Culinaromancer's Chest"

scope = "Shared"
stack = "Always"

sellMultiplier = 1300
buyMultiplier = 400
delta = 20

size = 21

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.chocolate_bar"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.cheese"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.tomato"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.cooking_apple"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.grapes"
count = 2
restockCycles = 500

[[inventory.stock]]
obj = "obj.pot_flour"
count = 2
restockCycles = 200

[[inventory.stock]]
obj = "obj.pizza_base"
count = 1
restockCycles = 500

[[inventory.stock]]
obj = "obj.egg"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.bucket_milk"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.pot_of_cream"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.pot_of_butter"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.spicespot"
count = 2
restockCycles = 500

[[inventory.stock]]
obj = "obj.piedish"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.cake_tin"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.bowl_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.jug_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.pack_jug_empty"
count = 1
restockCycles = 80

[[inventory.stock]]
obj = "obj.pot_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.cup_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.bucket_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.pack_bucket"
count = 2
restockCycles = 100

