[[inventory]]
isServerOnly = true
id = "inv.joeshop"
name = "Harpoon Joe's House of 'Rum'."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 20

size = 4

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.beer"
count = 3
restockCycles = 100

[[inventory.stock]]
obj = "obj.fever_rum"
count = 3
restockCycles = 100

[[inventory.stock]]
obj = "obj.jug_wine"
count = 1
restockCycles = 15000

[[inventory.stock]]
obj = "obj.stew"
count = 5
restockCycles = 150

