[[inventory]]
isServerOnly = true
id = "inv.keldagrim_clothes_shop"
name = "Agmundi Quality Clothes"

scope = "Shared"
stack = "Always"

sellMultiplier = 1300
buyMultiplier = 550
delta = 30

size = 10

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.dwarf_skirt2"
count = 3
restockCycles = 50

[[inventory.stock]]
obj = "obj.dwarf_skirt3"
count = 3
restockCycles = 50

[[inventory.stock]]
obj = "obj.dwarf_trousers2"
count = 3
restockCycles = 40

[[inventory.stock]]
obj = "obj.dwarf_trousers3"
count = 3
restockCycles = 40

[[inventory.stock]]
obj = "obj.dwarf_shorts2"
count = 3
restockCycles = 35

[[inventory.stock]]
obj = "obj.dwarf_shorts3"
count = 3
restockCycles = 35

[[inventory.stock]]
obj = "obj.dwarf_jumper2"
count = 3
restockCycles = 55

[[inventory.stock]]
obj = "obj.dwarf_jumper3"
count = 3
restockCycles = 55

[[inventory.stock]]
obj = "obj.dwarf_shirt2"
count = 3
restockCycles = 50

[[inventory.stock]]
obj = "obj.dwarf_shirt3"
count = 3
restockCycles = 50

