[[inventory]]
isServerOnly = true
id = "inv.lletyafoodshop1"
name = "Lletya Food Store"

scope = "Shared"
stack = "Always"

sellMultiplier = 1300
buyMultiplier = 400
delta = 30

size = 5

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.bread"
count = 10
restockCycles = 200

[[inventory.stock]]
obj = "obj.lobster"
count = 15
restockCycles = 200

[[inventory.stock]]
obj = "obj.jug_wine"
count = 3
restockCycles = 500

[[inventory.stock]]
obj = "obj.cheese"
count = 10
restockCycles = 200

[[inventory.stock]]
obj = "obj.cake"
count = 5
restockCycles = 200

