[[inventory]]
isServerOnly = true
id = "inv.pickaxeshop"
name = "Yarsul's Prodigious Pickaxes"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 20

size = 6

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.bronze_pickaxe"
count = 6
restockCycles = 50

[[inventory.stock]]
obj = "obj.iron_pickaxe"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.steel_pickaxe"
count = 4
restockCycles = 200

[[inventory.stock]]
obj = "obj.mithril_pickaxe"
count = 3
restockCycles = 300

[[inventory.stock]]
obj = "obj.adamant_pickaxe"
count = 2
restockCycles = 500

[[inventory.stock]]
obj = "obj.rune_pickaxe"
count = 1
restockCycles = 700

