[[inventory]]
isServerOnly = true
id = "inv.pizzabaseshop"
name = "Tony's Pizza Bases"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 30

size = 1

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.pizza_base"
count = 30
restockCycles = 100

