[[inventory]]
isServerOnly = true
id = "inv.ranging_guild_bowshop"
name = "Dargaud's Bow and Arrows."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 500
delta = 10

size = 27

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.arrow_shaft"
count = 1000
restockCycles = 50

[[inventory.stock]]
obj = "obj.bronze_arrowheads"
count = 500
restockCycles = 10

[[inventory.stock]]
obj = "obj.iron_arrowheads"
count = 400
restockCycles = 20

[[inventory.stock]]
obj = "obj.steel_arrowheads"
count = 300
restockCycles = 30

[[inventory.stock]]
obj = "obj.mithril_arrowheads"
count = 200
restockCycles = 40

[[inventory.stock]]
obj = "obj.adamant_arrowheads"
count = 200
restockCycles = 50

[[inventory.stock]]
obj = "obj.rune_arrowheads"
count = 150
restockCycles = 60

[[inventory.stock]]
obj = "obj.bronze_arrow"
count = 1000
restockCycles = 10

[[inventory.stock]]
obj = "obj.iron_arrow"
count = 500
restockCycles = 20

[[inventory.stock]]
obj = "obj.steel_arrow"
count = 500
restockCycles = 40

[[inventory.stock]]
obj = "obj.mithril_arrow"
count = 500
restockCycles = 60

[[inventory.stock]]
obj = "obj.adamant_arrow"
count = 450
restockCycles = 120

[[inventory.stock]]
obj = "obj.rune_arrow"
count = 400
restockCycles = 130

[[inventory.stock]]
obj = "obj.zogre_brutal_bronze"
count = 0
restockCycles = 1000

[[inventory.stock]]
obj = "obj.zogre_brutal_iron"
count = 0
restockCycles = 1000

[[inventory.stock]]
obj = "obj.zogre_brutal_steel"
count = 0
restockCycles = 1000

[[inventory.stock]]
obj = "obj.zogre_brutal_black"
count = 0
restockCycles = 1500

[[inventory.stock]]
obj = "obj.zogre_brutal_mithril"
count = 0
restockCycles = 2000

[[inventory.stock]]
obj = "obj.zogre_brutal_adamant"
count = 0
restockCycles = 3000

[[inventory.stock]]
obj = "obj.zogre_brutal_rune"
count = 0
restockCycles = 4000

[[inventory.stock]]
obj = "obj.shortbow"
count = 20
restockCycles = 50

[[inventory.stock]]
obj = "obj.oak_shortbow"
count = 20
restockCycles = 60

[[inventory.stock]]
obj = "obj.willow_shortbow"
count = 20
restockCycles = 70

[[inventory.stock]]
obj = "obj.longbow"
count = 20
restockCycles = 50

[[inventory.stock]]
obj = "obj.oak_longbow"
count = 20
restockCycles = 60

[[inventory.stock]]
obj = "obj.zogre_bow"
count = 0
restockCycles = 2000

[[inventory.stock]]
obj = "obj.willow_longbow"
count = 20
restockCycles = 70

