[[inventory]]
isServerOnly = true
id = "inv.regicide_general_shop"
name = "Quartermaster's Stores"

scope = "Shared"
stack = "Always"

sellMultiplier = 1300
buyMultiplier = 400
delta = 30

size = 14

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.pot_empty"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.jug_empty"
count = 2
restockCycles = 100

[[inventory.stock]]
obj = "obj.pack_jug_empty"
count = 5
restockCycles = 15

[[inventory.stock]]
obj = "obj.shears"
count = 3
restockCycles = 100

[[inventory.stock]]
obj = "obj.tinderbox"
count = 3
restockCycles = 100

[[inventory.stock]]
obj = "obj.bread"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.bronze_halberd"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.iron_halberd"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.steel_halberd"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.black_halberd"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.mithril_halberd"
count = 7
restockCycles = 100

[[inventory.stock]]
obj = "obj.adamant_halberd"
count = 7
restockCycles = 100

[[inventory.stock]]
obj = "obj.rune_halberd"
count = 7
restockCycles = 100

[[inventory.stock]]
obj = "obj.dragon_halberd"
count = 5
restockCycles = 500

