[[inventory]]
isServerOnly = true
id = "inv.shilofishingshop"
name = "Fernahei's Fishing Hut."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 700
delta = 10

size = 9

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.fishing_rod"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.fly_fishing_rod"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.fishing_bait"
count = 200
restockCycles = 1

[[inventory.stock]]
obj = "obj.pack_fishing_bait"
count = 30
restockCycles = 5

[[inventory.stock]]
obj = "obj.feather"
count = 800
restockCycles = 1

[[inventory.stock]]
obj = "obj.pack_feather"
count = 50
restockCycles = 2

[[inventory.stock]]
obj = "obj.raw_trout"
count = 0
restockCycles = 1500

[[inventory.stock]]
obj = "obj.raw_pike"
count = 0
restockCycles = 1800

[[inventory.stock]]
obj = "obj.raw_salmon"
count = 0
restockCycles = 2100

