[[inventory]]
isServerOnly = true
id = "inv.teashop"
name = "Ye olde Tea Shoppe."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 20

size = 1

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.cup_of_tea"
count = 20
restockCycles = 50

