[[inventory]]
isServerOnly = true
id = "inv.warguild_potion_shop"
name = "Warrior Guild Potion Shop"

scope = "Shared"
stack = "Always"

sellMultiplier = 1200
buyMultiplier = 150
delta = 20

size = 3

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.3dose1strength"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.3dose1attack"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.3dose1defense"
count = 10
restockCycles = 100

