[[inventory]]
isServerOnly = true
id = "inv.whiteknight_armoury2"
name = "White Knight Armoury"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 1000
delta = 0

size = 4

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.white_chainbody"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.white_platelegs"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.white_dagger"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.white_sword"
count = 10
restockCycles = 100

