[[inventory]]
isServerOnly = true
id = "inv.wildernesscapeshop7"
name = "Neil's Wilderness Cape Shop."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 10

size = 5

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.wilderness_cape_7"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_17"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_27"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_37"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_47"
count = 100
restockCycles = 100

