[[inventory]]
isServerOnly = true
id = "inv.wildernesscapeshop6"
name = "Richard's Wilderness Cape Shop."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 10

size = 5

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.wilderness_cape_6"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_16"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_26"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_36"
count = 100
restockCycles = 100

[[inventory.stock]]
obj = "obj.wilderness_cape_46"
count = 100
restockCycles = 100

