[[inventory]]
isServerOnly = true
id = "inv.wine_vinegar_merchant"
name = "Wine Shop."

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 600
delta = 20

size = 5

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.jug_wine"
count = 5
restockCycles = 1500

[[inventory.stock]]
obj = "obj.jug_empty"
count = 3
restockCycles = 100

[[inventory.stock]]
obj = "obj.pack_jug_empty"
count = 5
restockCycles = 15

[[inventory.stock]]
obj = "obj.rag_bottle_wine"
count = 2
restockCycles = 1500

[[inventory.stock]]
obj = "obj.rag_vinegar"
count = 500
restockCycles = 10

