[gamevals.varbit]
alchemy_anim_toggles=65472

[gamevals.varp]
herblore_amulet_chemistry=65497

[gamevals.queue]
herblore_clean = 56
herblore_unfinished = 51
herblore_finished = 52
herblore_crush = 53
herblore_swamp_tar = 54
herblore_barbarian_mix = 55

[gamevals.dbtable]
herblore_unfinished =65524
herblore_finished =65523
herblore_cleaning =65522
herblore_barbarian_mixes =65521
herblore_swamp_tar =65520
herblore_crushing =65519

[gamevals.dbrow]
herblore_guam_unfinished =65304
herblore_marrentill_unfinished =65303
herblore_tarromin_unfinished =65302
herblore_harralander_unfinished =65301
herblore_ranarr_unfinished =65300
herblore_toadflax_unfinished =65299
herblore_irit_unfinished =65298
herblore_avantoe_unfinished =65297
herblore_kwuarm_unfinished =65296
herblore_snapdragon_unfinished =65295
herblore_cadantine_unfinished =65294
herblore_lantadyme_unfinished =65293
herblore_dwarf_weed_unfinished =65292
herblore_torstol_unfinished =65291
herblore_attack_potion =65290
herblore_antipoison =65289
herblore_strength_potion =65288
herblore_restore_potion = 98136
herblore_energy_potion =65287
herblore_prayer_potion =65286
herblore_super_attack =65285
herblore_superantipoison =65284
herblore_fishing_potion =65283
herblore_super_energy =65282
herblore_super_strength =65281
herblore_weapon_poison =65280
herblore_super_restore =65279
herblore_super_defence =65278
herblore_antifire =65277
herblore_ranging_potion =65276
herblore_magic_potion =65275
herblore_zamorak_brew =65274
herblore_saradomin_brew =65273
herblore_defence_potion =65272
herblore_agility_potion =65271
herblore_combat_potion =65270
herblore_super_combat_potion =65269
herblore_clean_guam =65268
herblore_clean_marrentill =65267
herblore_clean_tarromin =65266
herblore_clean_harralander =65265
herblore_clean_ranarr =65264
herblore_clean_toadflax =65263
herblore_clean_irit =65262
herblore_clean_avantoe =65261
herblore_clean_kwuarm =65260
herblore_clean_snapdragon =65259
herblore_clean_cadantine =65258
herblore_clean_lantadyme =65257
herblore_clean_dwarf_weed =65256
herblore_clean_torstol =65255
herblore_attack_mix =65254
herblore_antipoison_mix =65253
herblore_strength_mix =65252
herblore_stat_restore_mix =65251
herblore_energy_mix =65250
herblore_defence_mix =65249
herblore_agility_mix =65248
herblore_prayer_mix =65247
herblore_super_attack_mix =65246
herblore_super_antipoison_mix =65245
herblore_fishing_mix =65244
herblore_super_energy_mix =65243
herblore_super_strength_mix =65242
herblore_super_restore_mix =65241
herblore_super_defence_mix =65240
herblore_antifire_mix =65239
herblore_ranging_mix =65238
herblore_magic_mix =65237
herblore_zamorak_mix =65236
herblore_hunter_potion =65235
herblore_bastion_potion =65234
herblore_battlemage_potion =65233
herblore_super_antifire =65232
herblore_extended_antivenom_plus =65231
herblore_stamina_potion_1 =65230
herblore_stamina_potion_2 =65229
herblore_stamina_potion_3 =65228
herblore_stamina_potion_4 =65227
herblore_divine_bastion_1 =65226
herblore_divine_bastion_2 =65225
herblore_divine_bastion_3 =65224
herblore_divine_bastion_4 =65223
herblore_divine_battlemage_1 =65222
herblore_divine_battlemage_2 =65221
herblore_divine_battlemage_3 =65220
herblore_divine_battlemage_4 =65219
herblore_divine_magic_1 =65218
herblore_divine_magic_2 =65217
herblore_divine_magic_3 =65216
herblore_divine_magic_4 =65215
herblore_divine_ranging_1 =65214
herblore_divine_ranging_2 =65213
herblore_divine_ranging_3 =65212
herblore_divine_ranging_4 =65211
herblore_divine_super_attack_1 =65210
herblore_divine_super_attack_2 =65209
herblore_divine_super_attack_3 =65208
herblore_divine_super_attack_4 =65207
herblore_divine_super_combat_1 =65206
herblore_divine_super_combat_2 =65205
herblore_divine_super_combat_3 =65204
herblore_divine_super_combat_4 =65203
herblore_divine_super_defence_1 =65202
herblore_divine_super_defence_2 =65201
herblore_divine_super_defence_3 =65200
herblore_divine_super_defence_4 =65199
herblore_divine_super_strength_1 =65198
herblore_divine_super_strength_2 =65197
herblore_divine_super_strength_3 =65196
herblore_divine_super_strength_4 =65195
herblore_attack_mix_caviar =65194
herblore_guam_tar =65193
herblore_marrentill_tar =65192
herblore_tarromin_tar =65191
herblore_harralander_tar =65190
herblore_irit_tar =65189
herblore_crush_bird_nest =65188
herblore_crush_chocolate =65187
herblore_crush_unicorn_horn =65186
herblore_crush_dragon_scale =65185
herblore_crush_goat_horn =65184
herblore_crush_superior_dragon_bones =65183