[gamevals.dbtable]
slayer_masters=65518

[gamevals.enum]
slayer_toggleable_rewards=65475
slayer_task_tips=65535

[gamevals.param]
slayer_task_id=65507
slayer_task_tip=65527
slayer_superior=65521
available_in_wilderness=65522

[gamevals.varbit]
slayer_combat_check=65471
slayer_streak=65470
slayer_wildy_streak=65469
slayer_superior_active=65468
slayer_turael_intro_complete=65467
slayer_konar_intro_complete=65466
slayer_wilderness_assignment_briefed=65465
slayer_krystilia_edgeville_spawn_unlocked=65464
slayer_krystilia_edgeville_spawn_active=65463
slayer_duradel_notes_received=65462
slayer_task_tips=65461
slayer_expeditious_charges=65460
slayer_total_tasks_done=65459
slayer_slaughter_charges=65457

[gamevals.varp]
slayer_player_state=65496
slayer_last_target=65495
slayer_last_master=65494
slayer_last_area=65493
slayer_last_count=65492
slayer_dialogue_flags=65491

[gamevals.dbrow]
turael_aya=65182
spira=65181
krystilia=65180
mazchna_achtryn=65179
vannaka=65178
chaeldar=65177
konar=65176
nieve_steve=65175
duradel_kuradal=65174
