[gamevals.queue]
smithing_cannonball_smelt=65524
smithing_crystal_singing=65529
smithing_dragon_forge=65530
smithing_bar_smelt=65531
smithing_anvil=65532
smithing_anvil_open=65528

[gamevals.dbtable]
smithing_crystal_singing=65528
smithing_dragon_forge=65527
smithing_cannon_balls=65526
smithing_bars=65525

[gamevals.dbrow]

bow_of_faerdhinen_charged=65346
blade_of_saeldor_charged=65345
bow_of_faerdhinen=65344
blade_of_saeldor=65343
eternal_teleport_crystal=65342
enhanced_crystal_key=65341
crystal_shield=65340
crystal_halberd=65339
crystal_bow=65338
crystal_pickaxe=65337
crystal_harpoon=65336
crystal_felling_axe=65335
crystal_axe=65334
crystal_body=65333
crystal_legs=65332
crystal_helm=65331
crystal_celestial_signet=65330

dragon_keel_parts=65329
dragon_key=65328
dragon_kiteshield=65327
dragon_nails=65326
dragon_platebody=65325
large_dragon_keel_parts=65324

bronze_cannon_ball=65323
iron_cannon_ball=65322
steel_cannon_ball=65321
mithril_cannon_ball=65320
adamantite_cannon_ball=65319
runite_cannon_ball=65318

bronze=65317
blurite=65316
iron=65315
silver=65314
elemental=65313
lead=65312
steel=65311
gold=65310
lovakite=65309
mithril=65308
adamantite=65307
cupronickel=65306
runite=65305