[gamevals.dbtable]
stat_components=65532

[gamevals.dbrow]
firemaking_stat=65438
attack_stat=65437
crafting_stat=65436
fletching_stat=65435
hunter_stat=65434
magic_stat=65433
strength_stat=65432
ranged_stat=65431
farming_stat=65430
woodcutting_stat=65429
cooking_stat=65428
fishing_stat=65427
smithing_stat=65426
mining_stat=65425
prayer_stat=65424
slayer_stat=65423
hitpoints_stat=65422
defence_stat=65421
thieving_stat=65420
herblore_stat=65419
agility_stat=65418
construction_stat=65417
runecraft_stat=65416
sailing_stat=65415