[gamevals.dbtable]
skill_prayer=65535
prayer_blessed_bone=65534
prayer_ectofuntus_bonemeal=65533

[gamevals.queue]
prayer_ecto_collect_slime = 50
prayer_ecto_grinder = 49
prayer_libation_sacrifice = 45
prayer_make_sunfire_wine = 46
prayer_demonic_ruins_regen = 47
prayer_break_down_bone = 44
prayer_altar_sacrifice = 43
prayer_bury = 42

[gamevals.varbit]
ash_sanctifier_activity_enabled=65474
bonecrusher_activity_enabled=65473
ecto_grinder_recipe=65535
ecto_tokens=65534

[gamevals.varp]
ash_sanctifier_activity=65501
bonecrusher_activity=65500
ecto_tokens=65499
ecto_grinder_recipe=65498

[gamevals.dbrow]
infernalashes=65535
abyssalashes=65529
maliciousashes=65528
vileashes=65527
fiendishashes=65526
beardedgorillabones=65525
gorillabones=65524
mediumninjamonkeybones=65523
smallninjamonkeybones=65522
largezombiemonkeybones=65521
smallzombiemonkeybones=65520
bleachedbones=65519
bonesapeatoll=65518
alansbones=65517
superiordragonbones=65516
ourgbones=65515
dagannothbones=65514
hydrabones=65513
raurgbones=65512
lavadragonbones=65511
fayrgbones=65510
drakebones=65509
dragonbones=65508
wyvernbones=65507
wyrmbones=65506
babydragonbones=65505
shaikahanbones=65504
zogrebones=65503
wyrmlingbones=65502
jogrebones=65501
bigbones=65500
batbones=65499
monkeybones=65498
burntbones=65497
wolfbones=65496
bones=65495
prayer_bb_blessed_bones=65494
prayer_bb_blessed_bat_bones=65493
prayer_bb_blessed_big_bones=65492
prayer_bb_blessed_zogre_bones=65491
prayer_bb_blessed_babywyrm_bones=65490
prayer_bb_blessed_babydragon_bones=65489
prayer_bb_blessed_strykewyrm_bones=65488
prayer_bb_blessed_wyrm_bones=65487
prayer_bb_sun_kissed_bones=65486
prayer_bb_blessed_wyvern_bones=65485
prayer_bb_blessed_dragon_bones=65484
prayer_bb_blessed_drake_bones=65483
prayer_bb_blessed_fayrg_bones=65482
prayer_bb_blessed_lava_dragon_bones=65481
prayer_bb_blessed_raurg_bones=65480
prayer_bb_blessed_frost_dragon_bones=65479
prayer_bb_blessed_hydra_bones=65478
prayer_bb_blessed_dagannoth_bones=65477
prayer_bb_blessed_ourg_bones=65476
prayer_bb_blessed_superior_dragon_bones=65475
prayer_bb_blessed_bone_statuette=65474
prayer_ecto_alan_bones=65473
prayer_ecto_bones=65472
prayer_ecto_bat_bones=65471
prayer_ecto_big_bones=65470
prayer_ecto_long_bone=65469
prayer_ecto_curved_bone=65468
prayer_ecto_burnt_bones=65467
prayer_ecto_burnt_jogre_bones=65466
prayer_ecto_babydragon_bones=65465
prayer_ecto_wyrmling_bones=65464
prayer_ecto_dragon_bones=65463
prayer_ecto_wolf_bones=65462
prayer_ecto_small_ninja_monkey_bones=65461
prayer_ecto_medium_ninja_monkey_bones=65460
prayer_ecto_gorilla_bones=65459
prayer_ecto_bearded_gorilla_bones=65458
prayer_ecto_monkey_bones=65457
prayer_ecto_small_zombie_monkey_bones=65456
prayer_ecto_large_zombie_monkey_bones=65455
prayer_ecto_ape_atoll_skeleton_bones=65454
prayer_ecto_jogre_bones=65453
prayer_ecto_zogre_bones=65452
prayer_ecto_fayrg_bones=65451
prayer_ecto_raurg_bones=65450
prayer_ecto_ourg_bones=65449
prayer_ecto_shaikahan_bones=65448
prayer_ecto_dagannoth_bones=65447
prayer_ecto_wyvern_bones=65446
prayer_ecto_lava_dragon_bones=65445
prayer_ecto_superior_dragon_bones=65444
prayer_ecto_frost_dragon_bones=65443
prayer_ecto_wyrm_bones=65442
prayer_ecto_strykewyrm_bones=65441
prayer_ecto_drake_bones=65440
prayer_ecto_hydra_bones=65439