id = "Abyssal demon Standard and Catacombs of Kourend"
npcs = ["npc.slayer_abyssal", "npc.slayer_abyssal_strongholdcave", "npc.kourend_abyssal"]
areas = ["area.catacombs_of_kourend"]
brimstone_key_roll = true
brimstone_key_roll_konar_bonus = true

[main]
total = 128
name = "Abyssal demon Standard and Catacombs of Kourend"

[[main.entries]]
weight = 4
obj = "obj.black_sword"
count = 1

[[main.entries]]
weight = 3
obj = "obj.steel_battleaxe"
count = 1

[[main.entries]]
weight = 2
obj = "obj.black_axe"
count = 1

[[main.entries]]
weight = 1
obj = "obj.mithril_kiteshield"
count = 1

[[main.entries]]
weight = 1
obj = "obj.rune_chainbody"
count = 1

[[main.entries]]
weight = 1
obj = "obj.rune_med_helm"
count = 1

[[main.entries]]
weight = 8
obj = "obj.airrune"
count = 50

[[main.entries]]
weight = 7
obj = "obj.chaosrune"
count = 10

[[main.entries]]
weight = 4
obj = "obj.bloodrune"
count = 7

[[main.entries]]
weight = 1
obj = "obj.lawrune"
count = 3

[[main.entries]]
weight = 5
obj = "obj.cert_blankrune_high"
count = 60

[[main.entries]]
weight = 2
obj = "obj.adamantite_bar"
count = 1

[[main.entries]]
weight = 35
obj = "obj.coins"
count = 132

[[main.entries]]
weight = 9
obj = "obj.coins"
count = 220

[[main.entries]]
weight = 7
obj = "obj.coins"
count = 30

[[main.entries]]
weight = 6
obj = "obj.coins"
count = 44

[[main.entries]]
weight = 1
obj = "obj.coins"
count = 460

[[main.entries]]
weight = 2
obj = "obj.lobster"
count = 1

[[main.entries]]
weight = 1
obj = "obj.cosmic_talisman"
count = 1

[[main.entries]]
weight = 1
obj = "obj.chaos_talisman"
count = 1

[[main.entries]]
weight = 1
obj = "obj.3dose1defense"
count = 1

[[main.entries]]
weight = 19
shared = "herb"

[[main.entries]]
weight = 2
shared = "rareDrop"

[[main.entries]]
weight = 5
shared = "gem"

[[main.separate_rolls]]
numerator = 1
denominator = 512

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.abyssal_whip"
count = 1

[[main.separate_rolls]]
numerator = 1
denominator = 32000

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.abyssal_dagger"
count = 1

[[tertiary]]
numerator = 1
denominator = 25
obj = "obj.arceuus_corpse_abyssal"
count = 1

[[tertiary]]
numerator = 1
denominator = 6000
obj = "obj.poh_trophydrop_abyssaldemon"
count = 1

[[tertiary]]
numerator = 1
denominator = 121
obj = "obj.trail_clue_hard_map001"
count = 1
clue_scroll_box = true

[[tertiary]]
numerator = 1
denominator = 1140
obj = "obj.trail_elite_emote_exp1"
count = 1
clue_scroll_box = true
