id = "Cow Drops"
npcs = ["npc.cow", "npc.cow2", "npc.cow3", "npc.cow_beef", "npc.fairy_cow"]

[[guaranteed]]
obj = "obj.cow_hide"
count = 1

[[guaranteed]]
obj = "obj.raw_beef"
count = 1

[[tertiary]]
numerator = 1
denominator = 128
obj = "obj.trail_clue_beginner"
count = 1
clue_scroll_box = true
