id = "Crystalline Wolf Drops"
npcs = ["npc.crystal_wolf"]

[[guaranteed]]
obj = "obj.gauntlet_crystal_shard"
count = "50..105"


# Unknown wiki drop rate: Raw paddlefish [main/Materials/Common]
# Unknown wiki drop rate: Weapon frame [main/Materials/Common]
# Unknown wiki drop rate: Teleport crystal (The Gauntlet) [main/Other/Uncommon]
