id = "Daddy's special water Drops"
npcs = ["npc.sailing_charting_drink_troll_dad"]

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_troll_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"
