id = "Dinky the drink troll Drops"
npcs = ["npc.sailing_charting_drink_crate_fish_stoutier_effect"]

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_troll_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"
