id = "Harpie Bug Swarm Drops"
npcs = ["npc.slayer_harpiebugswarm"]

[main]
total = 128
name = "Harpie Bug Swarm Drops"

[[main.entries]]
weight = 4
obj = "obj.steel_axe"
count = 1

[[main.entries]]
weight = 4
obj = "obj.steel_full_helm"
count = 1

[[main.entries]]
weight = 3
obj = "obj.staff_of_fire"
count = 1

[[main.entries]]
weight = 2
obj = "obj.mithril_chainbody"
count = 1

[[main.entries]]
weight = 1
obj = "obj.adamant_med_helm"
count = 1

[[main.entries]]
weight = 1
obj = "obj.steel_armoured_boots"
count = 1

[[main.entries]]
weight = 20
obj = "obj.firerune"
count = 30

[[main.entries]]
weight = 8
obj = "obj.firerune"
count = 60

[[main.entries]]
weight = 5
obj = "obj.chaosrune"
count = 15

[[main.entries]]
weight = 3
obj = "obj.deathrune"
count = 3

[[main.entries]]
weight = 25
obj = "obj.coins"
count = 40

[[main.entries]]
weight = 20
obj = "obj.coins"
count = 160

[[main.entries]]
weight = 10
obj = "obj.coins"
count = 230

[[main.entries]]
weight = 7
obj = "obj.coins"
count = 30

[[main.entries]]
weight = 2
obj = "obj.coins"
count = 490

[[main.entries]]
weight = 8
obj = "obj.gold_ore"
count = 1

[[main.entries]]
weight = 2
obj = "obj.jug_wine"
count = 1

[[main.entries]]
weight = 3
shared = "gem"

[[tertiary]]
numerator = 1
denominator = 121
obj = "obj.trail_medium_emote_exp1"
count = 1
clue_scroll_box = true
