id = "Headless Beast Drops"
npcs = ["npc.ga_beast"]

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1
