id = "Ice troll Drops"
npcs = ["npc.trollromance_icetroll_melee1", "npc.trollromance_icetroll_melee2", "npc.trollromance_icetroll_melee3", "npc.trollromance_icetroll_melee4", "npc.trollromance_icetroll_melee5", "npc.trollromance_icetroll_melee6", "npc.trollromance_icetroll_melee7", "npc.trollrescue_icetroll_melee1", "npc.trollrescue_icetroll_melee2", "npc.trollrescue_icetroll_melee3", "npc.trollrescue_icetroll_melee4", "npc.trollrescue_icetroll_melee5", "npc.trollrescue_icetroll_melee6", "npc.trollrescue_icetroll_melee7"]

[main]
total = 128
name = "Ice troll Drops"

[[main.entries]]
weight = 4
obj = "obj.black_platebody"
count = 1

[[main.entries]]
weight = 2
obj = "obj.adamant_axe"
count = 1

[[main.entries]]
weight = 1
obj = "obj.adamant_kiteshield"
count = 1

[[main.entries]]
weight = 1
obj = "obj.black_warhammer"
count = 1

[[main.entries]]
weight = 1
obj = "obj.mithril_platebody"
count = 1

[[main.entries]]
weight = 1
obj = "obj.rune_battleaxe"
count = 1

[[main.entries]]
weight = 8
obj = "obj.bloodrune"
count = 2

[[main.entries]]
weight = 5
obj = "obj.bloodrune"
count = 5

[[main.entries]]
weight = 3
obj = "obj.lawrune"
count = 4

[[main.entries]]
weight = 1
obj = "obj.deathrune"
count = 15

[[main.entries]]
weight = 1
obj = "obj.waterrune"
count = 65

[[main.entries]]
weight = 29
obj = "obj.coins"
count = 30

[[main.entries]]
weight = 25
obj = "obj.coins"
count = 136

[[main.entries]]
weight = 10
obj = "obj.coins"
count = 200

[[main.entries]]
weight = 4
obj = "obj.coins"
count = 20

[[main.entries]]
weight = 3
obj = "obj.cert_lobster"
count = 6

[[main.entries]]
weight = 2
obj = "obj.raw_tuna"
count = 4

[[main.entries]]
weight = 1
nothing = true

[[main.entries]]
weight = 18
shared = "herb"

[[main.entries]]
weight = 8
shared = "gem"

[[tertiary]]
numerator = 1
denominator = 20
obj = "obj.arceuus_corpse_troll"
count = 1

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1
