id = "Long-tailed Wyvern Drops"
npcs = ["npc.wyvern_long_tailed"]
brimstone_key_roll = true
brimstone_key_roll_konar_bonus = true

[main]
total = 123
name = "Long-tailed Wyvern Drops"

[[main.entries]]
weight = 4
obj = "obj.air_battlestaff"
count = 1

[[main.entries]]
weight = 3
obj = "obj.cert_battlestaff"
count = "3..5"

[[main.entries]]
weight = 2
obj = "obj.adamant_battleaxe"
count = 1

[[main.entries]]
weight = 2
obj = "obj.adamant_full_helm"
count = 1

[[main.entries]]
weight = 2
obj = "obj.rune_pickaxe"
count = 1

[[main.entries]]
weight = 2
obj = "obj.adamant_platebody"
count = 1

[[main.entries]]
weight = 6
obj = "obj.adamant_arrow"
count = "38..42"

[[main.entries]]
weight = 4
obj = "obj.waterrune"
count = 50

[[main.entries]]
weight = 4
obj = "obj.chaosrune"
count = 15

[[main.entries]]
weight = 4
obj = "obj.lawrune"
count = 15

[[main.entries]]
weight = 4
obj = "obj.deathrune"
count = 15

[[main.entries]]
weight = 4
obj = "obj.bloodrune"
count = 15

[[main.entries]]
weight = 1
obj = "obj.soulrune"
count = 10

[[main.entries]]
weight = 1
obj = "obj.xbows_crossbow_bolts_runite"
count = "12..30"

[[main.entries]]
weight = 2
obj = "obj.unidentified_ranarr"
count = 1

[[main.entries]]
weight = 2
obj = "obj.unidentified_torstol"
count = 1

[[main.entries]]
weight = 2
obj = "obj.seaweed_seed"
count = 12

[[main.entries]]
weight = 8
obj = "obj.cert_blankrune_high"
count = 150

[[main.entries]]
weight = 6
obj = "obj.cert_adamantite_bar"
count = "2..4"

[[main.entries]]
weight = 6
obj = "obj.cert_teak_logs"
count = 35

[[main.entries]]
weight = 3
obj = "obj.cert_snape_grass"
count = "10..15"

[[main.entries]]
weight = 3
obj = "obj.cert_runite_ore"
count = "1..2"

[[main.entries]]
weight = 8
obj = "obj.lobster"
count = 2

[[main.entries]]
weight = 11
obj = "obj.coins"
count = 3000

[[main.entries]]
weight = 7
obj = "obj.4doseprayerrestore"
count = 1

[[main.entries]]
weight = 2
obj = "obj.xbows_crossbow_unstrung_adamantite"
count = 1

[[main.entries]]
weight = 2
obj = "obj.fossil_calcite"
count = 2

[[main.entries]]
weight = 2
obj = "obj.fossil_pyrophosphite"
count = 2

[[main.entries]]
weight = 2
obj = "obj.fossil_volcanic_ash"
count = "20..60"

[[main.entries]]
weight = 14
nothing = true

[[main.separate_rolls]]
numerator = 1
denominator = 512

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.granite_longsword"
count = 1

[[main.separate_rolls]]
numerator = 1
denominator = 2560

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.granite_boots"
count = 1

[[tertiary]]
numerator = 1
denominator = 12000
obj = "obj.wyvern_visage"
count = 1

[[tertiary]]
numerator = 1
denominator = 112
obj = "obj.trail_clue_hard_map001"
count = 1
clue_scroll_box = true


# Unknown wiki drop rate: Grimy kwuarm [main/Herbs/1/{{#expr:1/(40*{{#var:herbbase}}) round 1}}]
# Unknown wiki drop rate: Grimy cadantine [main/Herbs/1/{{#expr:1/(32*{{#var:herbbase}}) round 1}}]
# Unknown wiki drop rate: Grimy dwarf weed [main/Herbs/1/{{#expr:1/(32*{{#var:herbbase}}) round 1}}]
# Unknown wiki drop rate: Grimy lantadyme [main/Herbs/1/{{#expr:1/(24*{{#var:herbbase}}) round 1}}]
# Unknown wiki drop rate: Ranarr seed [main/Seeds/1/{{#expr:1/(15*{{#var:seedbase}} + 2/123) round 1}}]
# Unknown wiki drop rate: Snapdragon seed [main/Seeds/1/{{#expr:1/(14*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Torstol seed [main/Seeds/1/{{#expr:1/(11*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Watermelon seed [main/Seeds/1/{{#expr:1/(10*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Willow seed [main/Seeds/1/{{#expr:1/(10*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Mahogany seed [main/Seeds/1/{{#expr:1/(9*{{#var:seedbase}} + (1/123 * 1/3)) round 1}}]
# Unknown wiki drop rate: Maple seed [main/Seeds/1/{{#expr:1/(9*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Teak seed [main/Seeds/1/{{#expr:1/(9*{{#var:seedbase}} + (1/123 * 2/3)) round 1}}]
# Unknown wiki drop rate: Yew seed [main/Seeds/1/{{#expr:1/(9*{{#var:seedbase}} + 1/123) round 1}}]
# Unknown wiki drop rate: Papaya tree seed [main/Seeds/1/{{#expr:1/(7*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Magic seed [main/Seeds/1/{{#expr:1/(6*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Palm tree seed [main/Seeds/1/{{#expr:1/(5*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Spirit seed [main/Seeds/1/{{#expr:1/(4*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Dragonfruit tree seed [main/Seeds/1/{{#expr:1/(3*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Celastrus seed [main/Seeds/1/{{#expr:1/(2*{{#var:seedbase}}) round 1}}]
# Unknown wiki drop rate: Redwood tree seed [main/Seeds/1/{{#expr:1/(2*{{#var:seedbase}}) round 1}}]
# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (14 weight)
