id = "Mature custodian stalker Drops"
npcs = ["npc.mature_custodian_stalker"]

[main]
total = 107
name = "Mature custodian stalker Drops"

[[main.entries]]
weight = 15
obj = "obj.mcannonball"
count = "15..30"

[[main.entries]]
weight = 12
obj = "obj.airrune"
count = 150

[[main.entries]]
weight = 12
obj = "obj.firerune"
count = 100

[[main.entries]]
weight = 10
obj = "obj.rune_arrow"
count = "10..25"

[[main.entries]]
weight = 6
obj = "obj.deathrune"
count = "25..40"

[[main.entries]]
weight = 10
obj = "obj.cert_blankrune_high"
count = 20

[[main.entries]]
weight = 8
obj = "obj.monkfish"
count = "2..3"

[[main.entries]]
weight = 7
obj = "obj.custodian_broken_antler"
count = 1

[[main.entries]]
weight = 5
obj = "obj.cert_mithril_bar"
count = "5..10"

[[main.entries]]
weight = 4
obj = "obj.raw_beef"
count = 1

[[main.entries]]
weight = 1
obj = "obj.huasca_seed"
count = 1

[[main.entries]]
weight = 10
obj = "obj.coins"
count = "800..1050"

[[main.entries]]
weight = 1
shared = "rareDrop"

[[main.entries]]
weight = 6
shared = "gem"

[[tertiary]]
numerator = 1
denominator = 800
obj = "obj.custodian_antler_guard"
count = 1

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1
