id = "Mutated Terrorbird Drops"
npcs = ["npc.superior_warped_terrorbird"]

[[guaranteed]]
obj = "obj.konar_key"
count = 1
should_drop_brimstone_key = true

[main]
total = 64
name = "Mutated Terrorbird Drops"

[[main.entries]]
weight = 2
obj = "obj.adamnt_warhammer"
count = 1

[[main.entries]]
weight = 2
obj = "obj.adamant_platebody"
count = 1

[[main.entries]]
weight = 1
obj = "obj.rune_battleaxe"
count = 1

[[main.entries]]
weight = 1
obj = "obj.rune_kiteshield"
count = 1

[[main.entries]]
weight = 1
obj = "obj.rune_warhammer"
count = 1

[[main.entries]]
weight = 6
obj = "obj.airrune"
count = "80..120"

[[main.entries]]
weight = 6
obj = "obj.earthrune"
count = "80..100"

[[main.entries]]
weight = 3
obj = "obj.deathrune"
count = "15..20"

[[main.entries]]
weight = 3
obj = "obj.lawrune"
count = "15..20"

[[main.entries]]
weight = 3
obj = "obj.soulrune"
count = "10..15"

[[main.entries]]
weight = 8
obj = "obj.coins"
count = "600..800"

[[main.entries]]
weight = 2
obj = "obj.cert_adamantite_ore"
count = "3..5"

[[main.entries]]
weight = 3
obj = "obj.weapon_poison"
count = 1

[[main.entries]]
weight = 3
obj = "obj.xbows_bolt_tips_diamond"
count = "24..32"

[[main.entries]]
weight = 4
obj = "obj.feather"
count = "100..200"

[[main.entries]]
weight = 5
obj = "obj.cert_raw_shark"
count = "3..7"

[[main.entries]]
weight = 5
obj = "obj.swamp_tar"
count = "40..60"

[[main.entries]]
weight = 3
obj = "obj.chocolate_bomb"
count = "2..3"

[[main.entries]]
weight = 3
nothing = true

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_terrorbird_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"

[[tertiary]]
numerator = 1
denominator = 320
obj = "obj.warped_sceptre_uncharged"
count = 1


# Unknown wiki drop rate: Clue scroll (hard) [tertiary/Tertiary/Rare]
# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (3 weight)
