id = "Sea Snake Young Drops"
npcs = ["npc.royal_sea_snake_medium"]

[main]
total = 133
name = "Sea Snake Young Drops"

[[main.entries]]
weight = 2
obj = "obj.waterrune"
count = 15

[[main.entries]]
weight = 2
obj = "obj.mistrune"
count = 1

[[main.entries]]
weight = 2
obj = "obj.slayer_broad_arrows"
count = 4

[[main.entries]]
weight = 60
obj = "obj.coins"
count = 44

[[main.entries]]
weight = 11
obj = "obj.coins"
count = 32

[[main.entries]]
weight = 9
obj = "obj.coins"
count = 24

[[main.entries]]
weight = 7
obj = "obj.coins"
count = 23

[[main.entries]]
weight = 10
obj = "obj.adamant_dart_tip"
count = 2

[[main.entries]]
weight = 4
obj = "obj.fishing_bait"
count = 50

[[main.entries]]
weight = 4
obj = "obj.pearl_bolttips"
count = 3

[[main.entries]]
weight = 3
obj = "obj.water_orb"
count = 1

[[main.entries]]
weight = 4
obj = "obj.raw_bass"
count = 2

[[main.entries]]
weight = 2
obj = "obj.raw_lobster"
count = 1

[[main.entries]]
weight = 2
obj = "obj.seaweed"
count = 5

[[main.entries]]
weight = 2
obj = "obj.edible_seaweed"
count = 5

[[main.entries]]
weight = 1
obj = "obj.smalloysterpearls"
count = 2

[[main.entries]]
weight = 1
obj = "obj.bigoysterpearls"
count = 1

[[main.entries]]
weight = 1
obj = "obj.casket"
count = 1

[[main.entries]]
weight = 5
shared = "herb"

[[main.entries]]
weight = 1
shared = "gem"

[[tertiary]]
numerator = 1
denominator = 400
obj = "obj.dorgesh_construction_bone"
count = 1

[[tertiary]]
numerator = 1
denominator = 5013
obj = "obj.dorgesh_construction_bone_curved"
count = 1

[[tertiary]]
numerator = 1
denominator = 121
obj = "obj.trail_medium_emote_exp1"
count = 1
clue_scroll_box = true
