id = "Snake (desert) Drops"
npcs = ["npc.feud_desert_snake", "npc.feud_desert_snake_outside"]

[[tertiary]]
numerator = 1
denominator = 4
obj = "obj.rag_snake_bone"
count = 1
quest = "quest_ragandboneman2"
quest_mode = "during"
