id = "Twisted Banshee Drops"
npcs = ["npc.kourend_banshee"]

[main]
total = 128
name = "Twisted Banshee Drops"

[[main.entries]]
weight = 5
obj = "obj.battlestaff"
count = 1

[[main.entries]]
weight = 1
obj = "obj.adamant_kiteshield"
count = 1

[[main.entries]]
weight = 2
obj = "obj.air_battlestaff"
count = 1

[[main.entries]]
weight = 2
obj = "obj.adamant_mace"
count = 1

[[main.entries]]
weight = 2
obj = "obj.rune_dagger"
count = 1

[[main.entries]]
weight = 2
obj = "obj.rune_med_helm"
count = 1

[[main.entries]]
weight = 1
obj = "obj.rune_full_helm"
count = 1

[[main.entries]]
weight = 3
obj = "obj.cosmicrune"
count = 20

[[main.entries]]
weight = 2
obj = "obj.chaosrune"
count = 30

[[main.entries]]
weight = 1
obj = "obj.chaosrune"
count = 17

[[main.entries]]
weight = 1
obj = "obj.firerune"
count = 35

[[main.entries]]
weight = 21
obj = "obj.cert_blankrune_high"
count = 65

[[main.entries]]
weight = 1
obj = "obj.eye_of_newt"
count = 1

[[main.entries]]
weight = 1
obj = "obj.mithril_ore"
count = 1

[[main.entries]]
weight = 9
obj = "obj.coins"
count = 130

[[main.entries]]
weight = 7
obj = "obj.coins"
count = 35

[[main.entries]]
weight = 7
obj = "obj.coins"
count = 260

[[main.entries]]
weight = 5
obj = "obj.swordfish"
count = 1

[[main.entries]]
weight = 34
shared = "herb"

[[main.entries]]
weight = 2
shared = "gem"

[[main.entries]]
weight = 13
shared = "rareSeed"

[[main.entries]]
weight = 6
nothing = true

[[main.separate_rolls]]
numerator = 1
denominator = 256

[[main.separate_rolls.entries]]
weight = 1
obj = "obj.mystic_gloves_dark"
count = 1

[[main.separate_rolls]]
numerator = 5
denominator = 256

[[main.separate_rolls.entries]]
weight = 5
obj = "obj.airrune"
count = 30

[[tertiary]]
numerator = 1
denominator = 121
obj = "obj.trail_clue_hard_map001"
count = 1
clue_scroll_box = true


# Main table pool padding uses a nothing roll (F2P drops removed and/or subtable access missing from wiki parse) (6 weight)
