id = "Undead Lumberjack Drops"
npcs = ["npc.ttrek2_zombie_diff_1_ver_1_1", "npc.ttrek2_zombie_diff_1_ver_1_2", "npc.ttrek2_zombie_diff_1_ver_1_3", "npc.ttrek2_zombie_diff_1_ver_1_4", "npc.ttrek2_zombie_diff_1_ver_2_1", "npc.ttrek2_zombie_diff_1_ver_2_2", "npc.ttrek2_zombie_diff_1_ver_2_3", "npc.ttrek2_zombie_diff_1_ver_2_4", "npc.ttrek2_zombie_diff_2_ver_1_1", "npc.ttrek2_zombie_diff_2_ver_1_2", "npc.ttrek2_zombie_diff_2_ver_1_3", "npc.ttrek2_zombie_diff_2_ver_1_4", "npc.ttrek2_zombie_diff_2_ver_2_1", "npc.ttrek2_zombie_diff_2_ver_2_2", "npc.ttrek2_zombie_diff_2_ver_2_3", "npc.ttrek2_zombie_diff_2_ver_2_4", "npc.ttrek2_zombie_diff_3_ver_1_1", "npc.ttrek2_zombie_diff_3_ver_1_2", "npc.ttrek2_zombie_diff_3_ver_1_3", "npc.ttrek2_zombie_diff_3_ver_1_4", "npc.ttrek2_zombie_diff_3_ver_2_1", "npc.ttrek2_zombie_diff_3_ver_2_2", "npc.ttrek2_zombie_diff_3_ver_2_3", "npc.ttrek2_zombie_diff_3_ver_2_4", "npc.ttrek2_zombie_diff_4_ver_1_1", "npc.ttrek2_zombie_diff_4_ver_1_2", "npc.ttrek2_zombie_diff_4_ver_1_3", "npc.ttrek2_zombie_diff_4_ver_1_4", "npc.ttrek2_zombie_diff_4_ver_2_1", "npc.ttrek2_zombie_diff_4_ver_2_2", "npc.ttrek2_zombie_diff_4_ver_2_3", "npc.ttrek2_zombie_diff_4_ver_2_4", "npc.ttrek2_zombie_diff_5_ver_1_1", "npc.ttrek2_zombie_diff_5_ver_1_2", "npc.ttrek2_zombie_diff_5_ver_1_3", "npc.ttrek2_zombie_diff_5_ver_1_4", "npc.ttrek2_zombie_diff_5_ver_2_1", "npc.ttrek2_zombie_diff_5_ver_2_2", "npc.ttrek2_zombie_diff_5_ver_2_3", "npc.ttrek2_zombie_diff_5_ver_2_4", "npc.ttrek2_zombie_diff_6_ver_1_1", "npc.ttrek2_zombie_diff_6_ver_1_2", "npc.ttrek2_zombie_diff_6_ver_1_3", "npc.ttrek2_zombie_diff_6_ver_1_4", "npc.ttrek2_zombie_diff_6_ver_2_1", "npc.ttrek2_zombie_diff_6_ver_2_2", "npc.ttrek2_zombie_diff_6_ver_2_3", "npc.ttrek2_zombie_diff_6_ver_2_4", "npc.ttrek2_zombie_diff_7_ver_1_1", "npc.ttrek2_zombie_diff_7_ver_1_2", "npc.ttrek2_zombie_diff_7_ver_1_3", "npc.ttrek2_zombie_diff_7_ver_1_4", "npc.ttrek2_zombie_diff_7_ver_2_1", "npc.ttrek2_zombie_diff_7_ver_2_2", "npc.ttrek2_zombie_diff_7_ver_2_3", "npc.ttrek2_zombie_diff_7_ver_2_4", "npc.ttrek2_zombie_diff_8_ver_1_1", "npc.ttrek2_zombie_diff_8_ver_1_2", "npc.ttrek2_zombie_diff_8_ver_1_3", "npc.ttrek2_zombie_diff_8_ver_1_4", "npc.ttrek2_zombie_diff_8_ver_2_1", "npc.ttrek2_zombie_diff_8_ver_2_2", "npc.ttrek2_zombie_diff_8_ver_2_3", "npc.ttrek2_zombie_diff_8_ver_2_4", "npc.ttrek2_zombie_diff_9_ver_1_1", "npc.ttrek2_zombie_diff_9_ver_1_2", "npc.ttrek2_zombie_diff_9_ver_1_3", "npc.ttrek2_zombie_diff_9_ver_1_4", "npc.ttrek2_zombie_diff_9_ver_2_1", "npc.ttrek2_zombie_diff_9_ver_2_2", "npc.ttrek2_zombie_diff_9_ver_2_3", "npc.ttrek2_zombie_diff_9_ver_2_4"]

[[guaranteed]]
obj = "obj.woodplank"
count = 1

[main]
total = 4
name = "Undead Lumberjack Drops"

[[main.entries]]
weight = 1
obj = "obj.ramble_lumberjack_top"
count = 1

[[main.entries]]
weight = 1
obj = "obj.ramble_lumberjack_legs"
count = 1

[[main.entries]]
weight = 1
obj = "obj.ramble_lumberjack_hat"
count = 1

[[main.entries]]
weight = 1
obj = "obj.ramble_lumberjack_boots"
count = 1

[[tertiary]]
numerator = 1
denominator = 5000
obj = "obj.champions_challenge_zombie"
count = 1
