/**
 * Quest catalog for the side journal quest list.
 * F2P quest names match OSRS; members list covers remaining cache quests.
 */

export const F2P_QUEST_NAMES: readonly string[] = [
    "Cook's Assistant",
    "Demon Slayer",
    "Doric's Quest",
    "Dragon Slayer I",
    "Ernest the Chicken",
    "Goblin Diplomacy",
    "Imp Catcher",
    "The Knight's Sword",
    "Pirate's Treasure",
    "Prince Ali Rescue",
    "The Restless Ghost",
    "Romeo & Juliet",
    "Rune Mysteries",
    "Sheep Shearer",
    "Shield of Arrav",
    "Vampyre Slayer",
    "Witch's Potion",
    "Black Knights' Fortress",
];

/** Default overview text for quests without a server definition yet. */
export const QUEST_OVERVIEW_BY_NAME = new Map<string, string>([
    ["cook's assistant", "talking to the <col=800000>Cook</col> in <col=800000>Lumbridge Castle</col>."],
    ["demon slayer", "defeating the demon <col=800000>Delrith</col> with Silverlight in <col=800000>Varrock</col>."],
    ["doric's quest", "talking to <col=800000>Doric</col> at his home north of <col=800000>Falador</col>."],
    ["dragon slayer i", "proving yourself worthy to wield <col=800000>Dragon Slayer</col> equipment."],
    ["ernest the chicken", "rescuing <col=800000>Ernest</col> from <col=800000>Draynor Manor</col>."],
    ["goblin diplomacy", "settling a dispute between goblin generals north of <col=800000>Falador</col>."],
    ["imp catcher", "collecting beads for <col=800000>Wizard Mizgog</col> in the Wizards' Tower."],
    ["the knight's sword", "helping <col=800000>Sir Vyvin's squire</col> replace a lost sword."],
    ["pirate's treasure", "hunting treasure with <col=800000>Redbeard Frank</col> in <col=800000>Port Sarim</col>."],
    ["prince ali rescue", "rescuing <col=800000>Prince Ali</col> from Lady Keli's cells."],
    ["the restless ghost", "helping <col=800000>Father Aereck</col> with a ghost in the Lumbridge graveyard."],
    ["romeo & juliet", "helping <col=800000>Romeo</col> win the heart of <col=800000>Juliet</col> in Varrock."],
    ["rune mysteries", "helping the <col=800000>Duke of Lumbridge</col> with a matter at the Wizards' Tower."],
    ["sheep shearer", "talking to <col=800000>Fred the Farmer</col> north-west of <col=800000>Lumbridge</col>."],
    ["shield of arrav", "recovering the stolen <col=800000>Shield of Arrav</col> for Varrock."],
    ["vampyre slayer", "slaying <col=800000>Count Draynor</col> for the people of Draynor Village."],
    ["witch's potion", "helping <col=800000>Hetty the Witch</col> in Rimmington."],
    ["black knights' fortress", "spying on the <col=800000>Black Knights' Fortress</col> for Sir Amik Varze."],
    ["desert treasure", "uncovering the secrets of the <col=800000>Desert Treasure</col>."],
    ["legend's quest", "proving yourself a <col=800000>Legend</col> of Gielinor."],
    ["monkey madness i", "investigating the mysterious <col=800000>ape</col> at the Grand Tree."],
    ["recipe for disaster", "helping the <col=800000>Cook</col> save the Lumbridge kitchen."],
    ["underground pass", "braving the dangers of the <col=800000>Underground Pass</col>."],
    ["plague city", "investigating the plague in <col=800000>West Ardougne</col>."],
    ["biohazard", "continuing the investigation into the <col=800000>plague</col>."],
    ["waterfall quest", "exploring the mysterious <col=800000>Waterfall</col>."],
    ["tree gnome village", "helping the <col=800000>Tree Gnomes</col> against General Khazard."],
    ["fight arena", "rescuing <col=800000>Jeremy Servil</col> from the Fight Arena."],
    ["witch's house", "investigating the strange house in <col=800000>Taverley</col>."],
    ["lost city", "discovering the fabled city of <col=800000>Zanaris</col>."],
    ["heroes' quest", "joining the ranks of the <col=800000>Heroes' Guild</col>."],
    ["family crest", "recovering the <col=800000>Family Crest</col> for Dimintheis."],
    ["tribal totem", "investigating stolen <col=800000>totems</col> in Ardougne."],
    ["fishing contest", "entering the <col=800000>Hemenster</col> fishing contest."],
    ["clock tower", "repairing the <col=800000>Ardougne Clock Tower</col>."],
    ["hazeel cult", "investigating the <col=800000>Hazeel Cult</col> in Ardougne."],
    ["sheep herder", "containing a <col=800000>plague</col> among the sheep of Ardougne."],
    ["murder mystery", "solving a murder at the <col=800000>Sinclair Mansion</col>."],
    ["the grand tree", "saving the <col=800000>Grand Tree</col> of the gnomes."],
    ["watchtower", "investigating the <col=800000>Yanille Watchtower</col>."],
    ["big chompy bird hunting", "hunting a <col=800000>chompy bird</col> for Rantz."],
    ["elemental workshop i", "exploring the <col=800000>Elemental Workshop</col>."],
    ["priest in peril", "helping <col=800000>King Roald</col> restore access to Morytania."],
    ["nature spirit", "helping <col=800000>Drezel</col> bless the Mort Myre swamp."],
    ["death plateau", "helping the <col=800000>White Knights</col> against the trolls."],
    ["troll stronghold", "rescuing Godric from the <col=800000>Troll Stronghold</col>."],
    ["temple of ikov", "investigating the <col=800000>Temple of Ikov</col>."],
    ["the dig site", "excavating the <col=800000>Archaeological Dig Site</col>."],
    ["observatory quest", "helping the <col=800000>Observatory</col> professor."],
    ["jungle potion", "brewing a potion for <col=800000>Trufitus</col> on Karamja."],
    ["shilo village", "helping <col=800000>Mosol Rei</col> cleanse Shilo Village."],
    ["druidic ritual", "performing the <col=800000>Druidic Ritual</col> to learn Herblore."],
    ["dwarf cannon", "helping the <col=800000>dwarves</col> repair their cannon."],
    ["regicide", "continuing the elven questline through <col=800000>Isafdar</col>."],
    ["mournings end part i", "investigating the <col=800000>death of King Tyras</col>."],
    ["mournings end part ii", "restoring the <col=800000>Temple of Light</col>."],
    ["in aid of the myreque", "helping the <col=800000>Myreque</col> in Morytania."],
    ["creature of fenkenstrain", "helping <col=800000>Dr Fenkenstrain</col> with his creation."],
    ["ghosts ahoy", "helping the ghosts of <col=800000>Port Phasmatys</col>."],
    ["the feud", "infiltrating the <col=800000>Bandit Camp</col> in the desert."],
    ["icthlarin's little helper", "investigating strange happenings in the <col=800000>desert</col>."],
    ["the golem", "investigating the clay <col=800000>Golem</col> in the desert."],
    ["shadow of the storm", "banishing the demon <col=800000>Agrith-Naar</col>."],
    ["enakhra's lament", "exploring the temple of <col=800000>Enakhra</col>."],
    ["the fremennik trials", "proving yourself to the <col=800000>Fremennik</col>."],
    ["throne of miscellania", "helping <col=800000>Miscellania</col> choose a ruler."],
    ["royal trouble", "defending <col=800000>Miscellania</col> from invaders."],
    ["eagles' peak", "investigating the <col=800000>Eagles' Peak</col>."],
    ["animal magnetism", "helping <col=800000>Ava</col> with her research."],
    ["contact!", "infiltrating the <col=800000>Menaphite</col> underground."],
    ["the eyes of glouphrie", "uncovering gnome illusion magic."],
    ["darkness of hallowvale", "rescuing the citizens of <col=800000>Hallowvale</col>."],
    ["the giant dwarf", "helping the <col=800000>Red Axe</col> conspiracy investigation."],
    ["recruitment drive", "joining the <col=800000>Temple Knights</col>."],
    ["wanted!", "hunting the outlaw <col=800000>Solomon Lamescus</col>."],
    ["the fremennik isles", "exploring the islands north of Rellekka."],
    ["tears of guthix", "entering the cave of <col=800000>Guthix</col>."],
    ["zogre flesh eaters", "investigating the <col=800000>zogre</col> menace."],
    ["fairytale i - growing pains", "helping <col=800000>Growler</col> the farmer."],
    ["fairytale ii - cure a queen", "curing the <col=800000>Fairy Queen</col>."],
    ["lunar diplomacy", "establishing contact with the <col=800000>Moon Clan</col>."],
    ["the great brain robbery", "investigating the <col=800000>zombie pirates</col> of Harmony Island."],
    ["what lies below", "investigating the <col=800000>Surok Magis</col> plot."],
    ["olaf's quest", "helping <col=800000>Olaf the Bard</col>."],
    ["another slice of ham", "investigating the <col=800000>goblin</col> temple."],
    ["dream mentor", "helping <col=800000>Oneiromancer</col> on Lunar Isle."],
    ["grim tales", "helping <col=800000>Sylas</col> with his stories."],
    ["king's ransom", "investigating the disappearance of <col=800000>King Arthur</col>."],
    ["monkey madness ii", "defeating the demon <col=800000>Glough</col>."],
    ["client of kourend", "working for the <col=800000>Kourend</col> favour system."],
    ["bone voyage", "joining the <col=800000>Fossil Island</col> expedition."],
    ["the queen of thieves", "investigating crime in <col=800000>Hosidius</col>."],
    ["the depths of despair", "helping <col=800000>Artur Hosidius</col>."],
    ["dragon slayer ii", "hunting the dragon <col=800000>Vorkath</col>."],
    ["song of the elves", "uniting the elven clans of <col=800000>Tirannwn</col>."],
    ["sins of the father", "investigating the <col=800000>Myreque</col> tragedy."],
    ["a porcine of interest", "investigating pig disappearances in <col=800000>Ardougne</col>."],
    ["getting ahead", "helping <col=800000>Headless Beast</col> hunters."],
    ["below ice mountain", "exploring the caves below <col=800000>Ice Mountain</col>."],
    ["a night at the theatre", "investigating the <col=800000>Theatre of Blood</col>."],
    ["a kingdom divided", "investigating the schism in <col=800000>Great Kourend</col>."],
    ["land of the goblins", "exploring the <col=800000>Goblin</col> homeland."],
    ["path of ascension", "ascending the ranks of the <col=800000>Sunlit Vale</col>."],
    ["pandemonium", "surviving the challenges of <col=800000>Pandemonium</col>."],
]);

import { getQuestOverviewFromReference } from "./questReference";

export function getQuestOverviewFallback(displayName: string): string | undefined {
    return (
        getQuestOverviewFromReference(displayName) ??
        QUEST_OVERVIEW_BY_NAME.get(displayName.toLowerCase())
    );
}

export function isFreeQuest(displayName: string): boolean {
    return F2P_QUEST_NAMES.some((name) => name.toLowerCase() === displayName.toLowerCase());
}
