[gamevals.dbtable]
light_sources = 55535
firemaking_logs = 55536
firemaking_colored_logs = 55537
[gamevals.varcon]
firemaking_campfire_expiry_cycle = 3

[gamevals.queue]
firemaking_light = 40
firemaking_campfire_tend = 41

[gamevals.dbrow]
firemaking_ironwood_logs       =55525
firemaking_rosewood_logs       =55526
light_source_candle= 55527
light_source_black_candle= 55528
light_source_torch= 55529
light_source_candle_lantern= 55530
light_source_candle_lantern_black= 55531
light_source_oil_lamp= 55532
light_source_oil_lantern= 55533
light_source_bullseye_lantern= 55534
light_source_mining_helmet= 55535
firemaking_normal_logs        = 55536
firemaking_achey_tree_logs    = 55537
firemaking_oak_logs           = 55538
firemaking_willow_logs        = 55539
firemaking_teak_logs          = 55540
firemaking_arctic_pine_logs   = 55541
firemaking_maple_logs         = 55542
firemaking_mahogany_logs      = 55543
firemaking_yew_logs           = 55544
firemaking_blisterwood_logs   = 55545
firemaking_magic_logs         = 55546
firemaking_redwood_logs       = 55547
firemaking_blue_logs          = 55548
firemaking_green_logs         = 55549
firemaking_purple_logs        = 55550
firemaking_red_logs           = 55551
firemaking_white_logs         = 55552
firemaking_colored_logs_blue              = 55553
firemaking_colored_logs_green             = 55554
firemaking_colored_logs_purple            = 55555
firemaking_colored_logs_red               = 55556
firemaking_colored_logs_white             = 55557
